import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import {
  ArrowUpRight, BadgeCheck, Bell, CalendarDays, Check, ChevronRight, CircleHelp, Copy,
  CreditCard, Crown, Download, Gift, Globe2, Headphones, Home, Languages, Link2, LoaderCircle,
  LockKeyhole, LogOut, Mail, Menu, MessageCircle, MonitorSmartphone, Moon, MoreHorizontal,
  Pencil, Plus, QrCode, Router, ScanLine, Send, Shield, ShieldCheck, Smartphone, Sparkles,
  Sun, TicketCheck, TicketPlus, Trash2, Upload, UserPlus, UserRound, UsersRound, Wifi, WifiOff,
  X, Zap, type LucideIcon,
} from "lucide-react";
import { api, demoMode, hasSession, idempotencyKey, logout, startEmailLogin, uploadPaymentEvidence, verifyEmailLogin } from "./api";
import { useI18n } from "./i18n";
import type {
  Device, FamilyGroup, Locale, Overview, Payment, Plan, PromoPreview, ReferralStatistics,
  Section, Theme, Ticket, TicketDetail, VpnConfig,
} from "./types";

interface LoadState<T> { data: T | null; loading: boolean; error: string | null }

function useResource<T>(path: string): LoadState<T> & { reload: () => void; setData: (value: T) => void } {
  const [revision, setRevision] = useState(0);
  const [state, setState] = useState<LoadState<T>>({ data: null, loading: true, error: null });
  useEffect(() => {
    let active = true; setState((value) => ({ ...value, loading: true, error: null }));
    api<T>(path).then((data) => active && setState({ data, loading: false, error: null })).catch((error: unknown) => active && setState({ data: null, loading: false, error: error instanceof Error ? error.message : "Request failed" }));
    return () => { active = false; };
  }, [path, revision]);
  return { ...state, reload: () => setRevision((value) => value + 1), setData: (data) => setState({ data, loading: false, error: null }) };
}

const navigation: Array<{ id: Section; icon: LucideIcon; en: string; ru: string }> = [
  { id: "overview", icon: Home, en: "Overview", ru: "Главная" },
  { id: "subscription", icon: Crown, en: "Subscription", ru: "Подписка" },
  { id: "devices", icon: MonitorSmartphone, en: "Devices", ru: "Устройства" },
  { id: "family", icon: UsersRound, en: "Family", ru: "Семья" },
  { id: "rewards", icon: Gift, en: "Rewards", ru: "Бонусы" },
  { id: "support", icon: Headphones, en: "Support", ru: "Поддержка" },
];

const validSections = new Set<Section>([...navigation.map((item) => item.id), "profile"]);
const sectionFromHash = (): Section => { const value = window.location.hash.slice(1) as Section; return validSections.has(value) ? value : "overview"; };

export default function App() {
  const { locale, setLocale, t } = useI18n();
  const [authenticated, setAuthenticated] = useState(hasSession());
  const [section, setSection] = useState<Section>(sectionFromHash());
  const [theme, setTheme] = useState<Theme>(() => localStorage.getItem("hazbit-customer-theme") === "light" ? "light" : "dark");
  const [menu, setMenu] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const overview = useResource<Overview>("/portal/overview");

  useEffect(() => { const change = () => setSection(sectionFromHash()); window.addEventListener("hashchange", change); return () => window.removeEventListener("hashchange", change); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("hazbit-customer-theme", theme); }, [theme]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 2800); return () => window.clearTimeout(timer); }, [toast]);
  const navigate = (value: Section) => { window.location.hash = value; setSection(value); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); };

  if (!authenticated) return <Login onDone={() => { setAuthenticated(true); overview.reload(); }} />;
  const active = navigation.find((item) => item.id === section);
  const name = overview.data?.user.public_name ?? overview.data?.user.email?.split("@")[0] ?? "Hazbit";
  const page = section === "overview" ? <OverviewPage overview={overview} navigate={navigate} notify={setToast} />
    : section === "subscription" ? <SubscriptionPage current={overview.data?.subscription ?? null} notify={setToast} />
    : section === "devices" ? <DevicesPage overview={overview.data} notify={setToast} />
    : section === "family" ? <FamilyPage identity={overview.data?.user.id ?? ""} subscriptionId={overview.data?.subscription?.id ?? null} notify={setToast} />
    : section === "rewards" ? <RewardsPage notify={setToast} />
    : section === "support" ? <SupportPage notify={setToast} />
    : <ProfilePage overview={overview.data} theme={theme} setTheme={setTheme} onLogout={() => { void logout().finally(() => setAuthenticated(false)); }} />;

  return <div className="customer-shell">
    <aside className={`customer-sidebar ${menu ? "open" : ""}`}>
      <Brand />
      <nav aria-label={t("Customer sections", "Разделы кабинета")}>{navigation.map(({ id, icon: Icon, en, ru }) => <button key={id} className={section === id ? "active" : ""} onClick={() => navigate(id)}><Icon size={18} /><span>{t(en, ru)}</span>{id === "support" && overview.data?.open_ticket_count ? <b>{overview.data.open_ticket_count}</b> : null}</button>)}</nav>
      <div className="sidebar-signal"><span><i /> {t("Protected", "Под защитой")}</span><small>{t("Traffic is routed securely", "Трафик защищён и зашифрован")}</small></div>
      <button className="sidebar-profile" onClick={() => navigate("profile")}><span>{initials(name)}</span><div><b>{name}</b><small>{overview.data?.user.email ?? t("Profile", "Профиль")}</small></div><ChevronRight size={16} /></button>
    </aside>
    {menu && <button className="nav-scrim" aria-label={t("Close menu", "Закрыть меню")} onClick={() => setMenu(false)} />}
    <main className="customer-main">
      <header className="customer-topbar">
        <button className="icon-button mobile-menu" onClick={() => setMenu(true)} aria-label={t("Open menu", "Открыть меню")}><Menu size={19} /></button>
        <div><p>{active ? t(active.en, active.ru) : t("Profile", "Профиль")}</p><h1>{greeting(locale, name)}</h1></div>
        <div className="top-actions">
          {demoMode && <span className="demo-label"><Sparkles size={13} /> Demo</span>}
          <div className="language-toggle" role="group" aria-label={t("Interface language", "Язык интерфейса")}><Languages size={14} /><button className={locale === "ru" ? "active" : ""} aria-pressed={locale === "ru"} onClick={() => setLocale("ru")}>RU</button><button className={locale === "en" ? "active" : ""} aria-pressed={locale === "en"} onClick={() => setLocale("en")}>EN</button></div>
          <button className="icon-button" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label={t("Change theme", "Сменить тему")}>{theme === "dark" ? <Sun size={17} /> : <Moon size={17} />}</button>
          <button className="icon-button notification-button" aria-label={t("Notifications", "Уведомления")} onClick={() => setToast(t("You are all caught up", "Новых уведомлений нет"))}><Bell size={17} /><i /></button>
        </div>
      </header>
      <div className="customer-content">{page}</div>
    </main>
    <nav className="mobile-dock" aria-label={t("Mobile navigation", "Мобильная навигация")}>{navigation.slice(0, 5).map(({ id, icon: Icon, en, ru }) => <button key={id} className={section === id ? "active" : ""} onClick={() => navigate(id)}><Icon size={20} /><span>{t(en, ru)}</span></button>)}</nav>
    {toast && <div className="toast"><Check size={16} /> {toast}</div>}
  </div>;
}

function Login({ onDone }: { onDone: () => void }) {
  const { locale, setLocale, t } = useI18n(); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [step, setStep] = useState<"email" | "code">("email"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { if (step === "email") { await startEmailLogin(email); setStep("code"); } else { await verifyEmailLogin(email, code); onDone(); } } catch (value) { setError(value instanceof Error ? value.message : t("Unable to sign in", "Не удалось войти")); } finally { setBusy(false); } };
  return <main className="login-page"><div className="login-aurora" /><section className="login-story"><Brand /><div><span className="eyebrow"><ShieldCheck size={14} /> {t("Private by design", "Приватность по умолчанию")}</span><h1>{t("Your private line to the open internet.", "Ваша приватная линия в открытый интернет.")}</h1><p>{t("One quiet place for your connection, devices and the people you protect.", "Спокойное пространство для подключения, устройств и тех, кого вы защищаете.")}</p></div><div className="login-trust"><span><LockKeyhole size={15} /> AES-256</span><span><Zap size={15} /> WireGuard</span><span><Globe2 size={15} /> 99.98% uptime</span></div></section><section className="login-panel"><div className="login-language"><button onClick={() => setLocale(locale === "ru" ? "en" : "ru")}>{locale.toUpperCase()} <Languages size={14} /></button></div><form className="login-card" onSubmit={submit}><div className="login-symbol"><Wifi size={23} /></div><p className="eyebrow">HAZBIT ACCESS</p><h2>{step === "email" ? t("Welcome back", "С возвращением") : t("Check your inbox", "Проверьте почту")}</h2><p>{step === "email" ? t("We will send a one-time access code. No password needed.", "Отправим одноразовый код. Пароль не нужен.") : t(`Enter the code sent to ${email}.`, `Введите код, отправленный на ${email}.`)}</p>{step === "email" ? <label>{t("Email", "Электронная почта")}<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required autoFocus /></label> : <label>{t("One-time code", "Одноразовый код")}<input className="otp" inputMode="numeric" pattern="[0-9]{6,8}" value={code} onChange={(event) => setCode(event.target.value)} placeholder="000000" required autoFocus /></label>}{error && <div className="inline-error">{error}</div>}<button className="primary-button login-button" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <ArrowUpRight size={17} />} {step === "email" ? t("Continue securely", "Продолжить безопасно") : t("Open Hazbit", "Открыть Hazbit")}</button>{step === "code" && <button type="button" className="text-button" onClick={() => setStep("email")}>{t("Use another email", "Указать другую почту")}</button>}<small><LockKeyhole size={12} /> {t("Protected by rotating sessions and device controls", "Защищено ротацией сессий и контролем устройств")}</small></form></section></main>;
}

function OverviewPage({ overview, navigate, notify }: { overview: LoadState<Overview> & { reload: () => void }; navigate: (section: Section) => void; notify: (value: string) => void }) {
  const { locale, t } = useI18n(); const data = overview.data;
  if (!data) return <ResourceState state={overview} />;
  const connected = data.vpn?.observed_status === "active"; const end = data.subscription?.current_period_ends_at ?? null; const days = end ? Math.max(0, Math.ceil((new Date(end).getTime() - Date.now()) / 86_400_000)) : 0;
  return <div className="page-stack overview-page"><section className="connection-hero"><div className="hero-copy"><span className="eyebrow"><i className="live-dot" /> {connected ? t("Secure tunnel active", "Защищённый туннель активен") : t("Ready to connect", "Готово к подключению")}</span><h2>{connected ? t("You are protected.", "Вы под защитой.") : t("Your connection is paused.", "Подключение приостановлено.")}</h2><p>{connected ? t("Your traffic is encrypted and your private route is stable.", "Трафик зашифрован, приватный маршрут работает стабильно.") : t("Open the VPN client to restore your private route.", "Откройте VPN-клиент, чтобы восстановить приватный маршрут.")}</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate("devices")}><Download size={16} /> {t("Set up a device", "Настроить устройство")}</button><button className="glass-button" onClick={() => notify(t("Connection status refreshed", "Статус подключения обновлён"))}><ScanLine size={16} /> {t("Check signal", "Проверить сигнал")}</button></div></div><SignalOrb connected={connected} /><div className="hero-meta"><span><Globe2 size={15} /> Amsterdam · 24 ms</span><span><Shield size={15} /> WireGuard</span></div></section>
    <section className="overview-grid"><article className="surface-card subscription-glance"><header><div><p className="eyebrow">{t("Current access", "Текущий доступ")}</p><h3>{data.subscription?.plan_name ?? t("No subscription", "Нет подписки")}</h3></div><Status value={data.subscription?.status ?? "inactive"} /></header><div className="days-ring" style={{ "--progress": `${Math.min(100, days / 60 * 100)}%` } as React.CSSProperties}><strong>{days}</strong><span>{t("days left", "дней осталось")}</span></div><div className="card-row"><span><CalendarDays size={15} /> {t("Valid until", "Действует до")}</span><b>{date(end, locale)}</b></div><button className="card-link" onClick={() => navigate("subscription")}>{t("Manage subscription", "Управлять подпиской")} <ChevronRight size={15} /></button></article>
      <article className="surface-card device-glance"><header><div><p className="eyebrow">{t("Your perimeter", "Ваш периметр")}</p><h3>{t("Trusted devices", "Доверенные устройства")}</h3></div><MonitorSmartphone size={20} /></header><div className="big-number"><strong>{data.active_device_count}</strong><span>/ {data.subscription?.device_limit ?? 0}</span></div><div className="usage-track"><i style={{ width: `${Math.min(100, data.active_device_count / Math.max(1, data.subscription?.device_limit ?? 1) * 100)}%` }} /></div><p>{t("Every active device shares your encrypted allowance.", "Все активные устройства используют общий защищённый лимит.")}</p><button className="card-link" onClick={() => navigate("devices")}>{t("Open devices", "Открыть устройства")} <ChevronRight size={15} /></button></article>
      <article className="surface-card family-glance"><header><div><p className="eyebrow">{t("Shared protection", "Общая защита")}</p><h3>{data.family_group_name ?? t("Create a family", "Создайте семью")}</h3></div><UsersRound size={20} /></header><div className="family-constellation"><span>A</span><span>T</span><span>S</span><i><Plus size={15} /></i></div><p>{data.family_group_id ? t("Your household shares one subscription without sharing accounts.", "Семья использует одну подписку без передачи аккаунтов.") : t("Invite people you trust and share protection.", "Пригласите близких и поделитесь защитой.")}</p><button className="card-link" onClick={() => navigate("family")}>{t("Manage family", "Управлять семьёй")} <ChevronRight size={15} /></button></article>
    </section>
    <section className="quick-grid"><button onClick={() => navigate("rewards")}><span className="quick-icon violet"><Gift size={19} /></span><div><b>{t("Invite & earn", "Приглашайте и получайте дни")}</b><small>{t("30 bonus days earned", "Получено 30 бонусных дней")}</small></div><ArrowUpRight size={16} /></button><button onClick={() => navigate("support")}><span className="quick-icon amber"><MessageCircle size={19} /></span><div><b>{t("Talk to support", "Написать в поддержку")}</b><small>{data.open_ticket_count ? t(`${data.open_ticket_count} conversation needs you`, `${data.open_ticket_count} обращение ждёт вас`) : t("We usually reply in 5 minutes", "Обычно отвечаем за 5 минут")}</small></div><ArrowUpRight size={16} /></button></section>
  </div>;
}

function SubscriptionPage({ current, notify }: { current: Overview["subscription"]; notify: (value: string) => void }) {
  const { locale, t } = useI18n(); const plans = useResource<Plan[]>("/portal/plans"); const payments = useResource<Payment[]>("/portal/payments"); const [selected, setSelected] = useState<{ plan: Plan; priceId: string } | null>(null);
  return <div className="page-stack"><PageIntro eyebrow={t("Access plans", "Тарифы доступа")} title={t("Choose your protection", "Выберите уровень защиты")} text={t("Upgrade without losing your devices, family or remaining time.", "Меняйте тариф без потери устройств, семьи и оставшегося времени.")} />
    {!plans.data ? <ResourceState state={plans} /> : <section className="plan-grid">{plans.data.map((plan) => { const active = current?.plan_slug === plan.slug; const price = plan.prices[0]; return <article className={`plan-card ${plan.slug} ${active ? "current" : ""}`} key={plan.id}>{active && <span className="current-flag"><BadgeCheck size={13} /> {t("Current plan", "Текущий тариф")}</span>}<header><p>0{plans.data!.indexOf(plan) + 1}</p><h3>{plan.name}</h3></header><p>{t(plan.description ?? "Private access", plan.slug === "family" ? "Один защищённый периметр для близких и всех устройств." : plan.slug === "premium" ? "Больше устройств, быстрые маршруты и усиленная защита." : "Приватный доступ для одного человека и повседневных задач.")}</p><div className="plan-price"><strong>{money(price?.amount_minor ?? 0, price?.currency ?? "RUB", locale)}</strong><span>/ {t("month", "месяц")}</span></div><ul><li><Check size={15} /> {plan.device_limit} {t("devices", "устройств")}</li><li><Check size={15} /> {plan.family_member_limit ? `${plan.family_member_limit} ${t("family members", "участников семьи")}` : t("Personal access", "Личный доступ")}</li><li><Check size={15} /> {t("Unlimited traffic", "Безлимитный трафик")}</li></ul><button className={active ? "quiet-button" : "primary-button"} disabled={active || !price} onClick={() => price && setSelected({ plan, priceId: price.id })}>{active ? t("Active", "Активен") : t("Choose plan", "Выбрать тариф")}</button></article>; })}</section>}
    <section className="surface-card history-card"><header><div><p className="eyebrow">{t("Billing history", "История платежей")}</p><h3>{t("Recent payments", "Последние платежи")}</h3></div><CreditCard size={20} /></header>{payments.data?.length ? <div className="payment-list">{payments.data.map((payment) => <div key={payment.id}><span className="payment-icon"><CreditCard size={17} /></span><div><b>{money(payment.amount_minor, payment.currency, locale)}</b><small>{date(payment.created_at, locale)} · {shortId(payment.id)}</small></div><Status value={payment.status} /></div>)}</div> : <Empty icon={CreditCard} text={t("No payments yet", "Платежей пока нет")} />}</section>
    {selected && <PaymentDialog selection={selected} onClose={() => setSelected(null)} onDone={() => { setSelected(null); payments.reload(); notify(t("Receipt accepted for verification", "Чек принят на проверку")); }} />}
  </div>;
}

function PaymentDialog({ selection, onClose, onDone }: { selection: { plan: Plan; priceId: string }; onClose: () => void; onDone: () => void }) {
  const { locale, t } = useI18n(); const price = selection.plan.prices.find((item) => item.id === selection.priceId)!; const [promo, setPromo] = useState(""); const [preview, setPreview] = useState<PromoPreview | null>(null); const [paymentId, setPaymentId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const checkPromo = async () => { setBusy(true); setError(null); try { setPreview(await api<PromoPreview>("/promo-codes/preview", { method: "POST", body: JSON.stringify({ code: promo, plan_price_id: price.id }) })); } catch (value) { setError(value instanceof Error ? value.message : "Promo failed"); } finally { setBusy(false); } };
  const create = async () => { setBusy(true); setError(null); try { const result = await api<{ id: string }>("/payments/intents", { method: "POST", headers: { "Idempotency-Key": idempotencyKey("payment") }, body: JSON.stringify({ plan_price_id: price.id, promo_code: preview?.code ?? null }) }); setPaymentId(result.id); } catch (value) { setError(value instanceof Error ? value.message : "Payment failed"); } finally { setBusy(false); } };
  const upload = async (file: File) => { if (!paymentId) return; setBusy(true); setError(null); try { await uploadPaymentEvidence(paymentId, file); onDone(); } catch (value) { setError(value instanceof Error ? value.message : "Upload failed"); } finally { setBusy(false); } };
  const total = preview?.final_amount_minor ?? price.amount_minor;
  return <Modal onClose={onClose} className="payment-modal"><div className="modal-heading"><span className="modal-icon"><CreditCard size={20} /></span><div><p className="eyebrow">{t("Secure checkout", "Безопасная оплата")}</p><h2>{selection.plan.name}</h2></div></div>{!paymentId ? <><div className="checkout-summary"><span>{t("Plan", "Тариф")}<b>{selection.plan.name} · {price.term_months} {t("mo.", "мес.")}</b></span>{preview && <span>{t("Promo discount", "Скидка по промокоду")}<b className="positive">−{money(preview.discount_amount_minor ?? 0, price.currency, locale)}</b></span>}<span className="checkout-total">{t("Total", "Итого")}<strong>{money(total, price.currency, locale)}</strong></span></div><div className="promo-entry"><input value={promo} onChange={(event) => setPromo(event.target.value.toUpperCase())} placeholder={t("Promo code", "Промокод")} /><button onClick={checkPromo} disabled={busy || promo.length < 3}>{t("Apply", "Применить")}</button></div><p className="modal-note"><ShieldCheck size={14} /> {t("Create an intent, make the transfer and upload your receipt. Gemini Vision checks it before activation.", "Создайте платёж, выполните перевод и загрузите чек. Gemini Vision проверит его перед активацией.")}</p><button className="primary-button wide" onClick={create} disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <ArrowUpRight size={16} />} {t("Create payment", "Создать платёж")}</button></> : <div className="receipt-step"><span className="receipt-orb"><Upload size={25} /></span><h3>{t("Upload your receipt", "Загрузите чек")}</h3><p>{t("JPEG, PNG or WebP up to 8 MB. Personal details stay encrypted.", "JPEG, PNG или WebP до 8 МБ. Персональные данные остаются зашифрованными.")}</p><label className="upload-button">{busy ? <LoaderCircle className="spin" size={17} /> : <Upload size={17} />} {t("Choose receipt", "Выбрать чек")}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0])} /></label></div>}{error && <div className="inline-error">{error}</div>}</Modal>;
}

function DevicesPage({ overview, notify }: { overview: Overview | null; notify: (value: string) => void }) {
  const { locale, t } = useI18n(); const devices = useResource<Device[]>("/devices"); const config = useResource<VpnConfig>("/vpn/config"); const [adding, setAdding] = useState(false); const [busy, setBusy] = useState<string | null>(null); const active = devices.data?.filter((item) => item.status !== "revoked") ?? [];
  const remove = async (device: Device) => { setBusy(device.id); try { await api(`/devices/${device.id}`, { method: "DELETE", headers: { "Idempotency-Key": idempotencyKey("device-remove") } }); devices.reload(); notify(t("Device removal queued", "Удаление устройства поставлено в очередь")); } finally { setBusy(null); } };
  const copyConfig = async () => { if (!config.data) return; await navigator.clipboard.writeText(config.data.subscription_url); notify(t("Private setup link copied", "Приватная ссылка скопирована")); };
  return <div className="page-stack"><PageIntro eyebrow={t("Trusted perimeter", "Доверенный периметр")} title={t("Your devices", "Ваши устройства")} text={t("Each slot belongs to one device. Remove anything you do not recognize.", "Каждый слот закреплён за устройством. Удалите всё, что вам незнакомо.")} action={<button className="primary-button" onClick={() => setAdding(true)}><Plus size={16} /> {t("Add device", "Добавить устройство")}</button>} />
    <section className="device-capacity"><div><span className="eyebrow">{t("Shared allowance", "Общий лимит")}</span><h3>{active.length} / {overview?.subscription?.device_limit ?? 0} {t("slots in use", "слотов занято")}</h3></div><div className="capacity-dots">{Array.from({ length: overview?.subscription?.device_limit ?? 0 }, (_, index) => <i className={index < active.length ? "used" : ""} key={index} />)}</div></section>
    {!devices.data ? <ResourceState state={devices} /> : <section className="device-grid">{active.map((device) => <article className="device-card" key={device.id}><header><span className={`device-platform ${device.status}`}><DeviceIcon platform={device.platform} /></span><button className="icon-button" aria-label={t(`Remove ${device.label}`, `Удалить ${device.label}`)} disabled={busy === device.id} onClick={() => remove(device)}>{busy === device.id ? <LoaderCircle className="spin" size={16} /> : <Trash2 size={15} />}</button></header><h3>{device.label ?? t("Unnamed device", "Устройство без имени")}</h3><p>{device.platform ?? t("Unknown platform", "Неизвестная платформа")} · #{device.slot_number}</p><footer><Status value={device.status} /><small>{device.last_seen_at ? relative(device.last_seen_at, locale) : t("Provisioning", "Подключается")}</small></footer></article>)}</section>}
    <section className="setup-banner"><span className="setup-symbol"><QrCode size={27} /></span><div><p className="eyebrow">{t("Quick setup", "Быстрая настройка")}</p><h3>{t("Connect another app", "Подключить приложение")}</h3><p>{t("Copy your private subscription link and add it to the Hazbit or WireGuard client.", "Скопируйте приватную ссылку и добавьте её в Hazbit или WireGuard.")}</p></div><button className="glass-button" onClick={copyConfig}><Copy size={16} /> {t("Copy setup link", "Скопировать ссылку")}</button></section>
    {adding && <AddDeviceDialog onClose={() => setAdding(false)} onDone={() => { setAdding(false); devices.reload(); notify(t("Device slot reserved", "Слот устройства зарезервирован")); }} />}
  </div>;
}

function AddDeviceDialog({ onClose, onDone }: { onClose: () => void; onDone: () => void }) {
  const { t } = useI18n(); const [label, setLabel] = useState(""); const [platform, setPlatform] = useState("iOS"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { await api("/devices", { method: "POST", headers: { "Idempotency-Key": idempotencyKey("device-create") }, body: JSON.stringify({ hwid: crypto.randomUUID().replaceAll("-", "").slice(0, 24), label, platform, os_version: "unknown", device_model: label }) }); onDone(); } catch (value) { setError(value instanceof Error ? value.message : "Unable to add device"); } finally { setBusy(false); } };
  return <Modal onClose={onClose}><form onSubmit={submit}><div className="modal-heading"><span className="modal-icon"><Smartphone size={20} /></span><div><p className="eyebrow">{t("New secure slot", "Новый защищённый слот")}</p><h2>{t("Add a device", "Добавить устройство")}</h2></div></div><label className="field">{t("Device name", "Название устройства")}<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder={t("e.g. Work MacBook", "например, Рабочий MacBook")} required /></label><label className="field">{t("Platform", "Платформа")}<select value={platform} onChange={(event) => setPlatform(event.target.value)}><option>iOS</option><option>Android</option><option>macOS</option><option>Windows</option><option>Linux</option><option>Android TV</option></select></label>{error && <div className="inline-error">{error}</div>}<button className="primary-button wide" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Plus size={16} />} {t("Reserve slot", "Зарезервировать слот")}</button></form></Modal>;
}

function FamilyPage({ identity, subscriptionId, notify }: { identity: string; subscriptionId: string | null; notify: (value: string) => void }) {
  const { locale, t } = useI18n(); const family = useResource<FamilyGroup>("/family/group"); const [invite, setInvite] = useState(""); const [renaming, setRenaming] = useState(false); const [name, setName] = useState(""); const [busy, setBusy] = useState<string | null>(null); const group = family.data;
  useEffect(() => { if (group) setName(group.name); }, [group]);
  const mutate = async (path: string, init: RequestInit, success: string) => { setBusy(path); try { await api(path, init); family.reload(); notify(success); } finally { setBusy(null); } };
  const sendInvite = async (event: FormEvent) => { event.preventDefault(); if (!group) return; await mutate(`/family/groups/${group.id}/invitations`, { method: "POST", body: JSON.stringify({ invited_email: invite }) }, t("Invitation created", "Приглашение создано")); setInvite(""); };
  const createGroup = async () => {
    if (!subscriptionId) return;
    setBusy("create");
    try {
      const created = await api<FamilyGroup>("/family/groups", { method: "POST", body: JSON.stringify({ subscription_id: subscriptionId, name: t("My family", "Моя семья") }) });
      family.setData(created);
      notify(t("Family space created", "Семейное пространство создано"));
    } finally { setBusy(null); }
  };
  if (!group) return <div className="page-stack"><PageIntro eyebrow={t("Shared protection", "Общая защита")} title={t("Family", "Семья")} text={t("Give everyone a separate account inside one private perimeter.", "Создайте для каждого отдельный аккаунт внутри общего приватного периметра.")} /><section className="surface-card family-empty"><span className="modal-icon"><UsersRound size={24} /></span><h3>{t("Create your family space", "Создайте семейное пространство")}</h3><p>{subscriptionId ? t("Your current plan is ready for a shared family group.", "Текущий тариф готов к созданию семейной группы.") : t("Choose a Family plan first to unlock invitations.", "Сначала выберите семейный тариф, чтобы открыть приглашения.")}</p>{family.loading ? <LoaderCircle className="spin" size={20} /> : <button className="primary-button" disabled={!subscriptionId || Boolean(busy)} onClick={createGroup}><Plus size={16} /> {t("Create family", "Создать семью")}</button>}</section></div>;
  const owner = group.owner_user_id === identity; const pending = group.invitations.filter((item) => item.status === "pending");
  return <div className="page-stack"><section className="family-hero"><div><p className="eyebrow">{t("One private perimeter", "Один приватный периметр")}</p><div className="family-title"><h2>{group.name}</h2>{owner && <button className="icon-button" onClick={() => setRenaming(true)} aria-label={t("Rename family", "Переименовать семью")}><Pencil size={15} /></button>}</div><p>{t("Everyone keeps a separate account while sharing subscription limits.", "У каждого свой аккаунт, но лимиты подписки используются совместно.")}</p></div><div className="family-orbit"><span>A</span><i>T</i><i>S</i><b><ShieldCheck size={23} /></b></div></section>
    <section className="family-metrics"><div><span>{t("Members", "Участники")}</span><strong>{group.active_member_count} / {group.member_limit}</strong><div className="usage-track"><i style={{ width: `${group.active_member_count / group.member_limit * 100}%` }} /></div></div><div><span>{t("Devices", "Устройства")}</span><strong>{group.active_device_count} / {group.device_limit}</strong><div className="usage-track blue"><i style={{ width: `${group.active_device_count / group.device_limit * 100}%` }} /></div></div></section>
    <div className="family-columns"><section className="surface-card"><header><div><p className="eyebrow">{t("Household", "Состав семьи")}</p><h3>{t("Protected people", "Защищённые участники")}</h3></div><UsersRound size={20} /></header><div className="family-members">{group.members.map((member) => <div key={member.id}><span>{initials(member.email ?? "H")}</span><div><b>{member.email ?? t("Hazbit member", "Участник Hazbit")}</b><small>{member.role === "owner" ? t("Family owner", "Владелец семьи") : `${t("Joined", "В семье с")} ${date(member.joined_at, locale)}`}</small></div>{member.role === "owner" ? <Crown size={16} /> : owner ? <button className="icon-button" disabled={Boolean(busy)} aria-label={t(`Remove ${member.email}`, `Удалить ${member.email}`)} onClick={() => mutate(`/family/groups/${group.id}/members/${member.user_id}`, { method: "DELETE", body: JSON.stringify({ reason: "Removed by family owner" }) }, t("Member access removed", "Доступ участника отключён"))}><Trash2 size={14} /></button> : null}</div>)}</div></section>
      <section className="surface-card invite-card"><header><div><p className="eyebrow">{t("Invite safely", "Безопасное приглашение")}</p><h3>{t("Add someone you trust", "Добавьте близкого человека")}</h3></div><UserPlus size={20} /></header>{owner ? <form className="invite-form" onSubmit={sendInvite}><label>{t("Their email", "Электронная почта")}<div><Mail size={15} /><input type="email" value={invite} onChange={(event) => setInvite(event.target.value)} placeholder="person@example.com" required /><button disabled={Boolean(busy)}><Send size={15} /></button></div></label></form> : <p>{t("Only the family owner can invite new members.", "Только владелец семьи может приглашать участников.")}</p>}<div className="pending-list"><p className="eyebrow">{t("Pending", "Ожидают")} · {pending.length}</p>{pending.length ? pending.map((item) => <div key={item.id}><span className="mail-icon"><Mail size={15} /></span><div><b>{item.invited_email}</b><small>{t("Expires", "Истекает")} {date(item.expires_at, locale)}</small></div>{owner && <button className="icon-button" onClick={() => mutate(`/family/groups/${group.id}/invitations/${item.id}`, { method: "DELETE" }, t("Invitation revoked", "Приглашение отозвано"))}><X size={14} /></button>}</div>) : <small>{t("No invitations waiting", "Нет ожидающих приглашений")}</small>}</div></section></div>
    {renaming && <Modal onClose={() => setRenaming(false)}><form onSubmit={(event) => { event.preventDefault(); mutate(`/family/groups/${group.id}`, { method: "PATCH", body: JSON.stringify({ name }) }, t("Family renamed", "Название семьи изменено")); setRenaming(false); }}><div className="modal-heading"><span className="modal-icon"><Pencil size={20} /></span><div><p className="eyebrow">{t("Family identity", "Название семьи")}</p><h2>{t("Rename group", "Переименовать группу")}</h2></div></div><label className="field">{t("Name", "Название")}<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} maxLength={120} required /></label><button className="primary-button wide"><Check size={16} /> {t("Save name", "Сохранить название")}</button></form></Modal>}
  </div>;
}

function RewardsPage({ notify }: { notify: (value: string) => void }) {
  const { locale, t } = useI18n(); const stats = useResource<ReferralStatistics>("/referrals/statistics"); const [promo, setPromo] = useState(""); const [preview, setPreview] = useState<PromoPreview | null>(null); const [error, setError] = useState<string | null>(null);
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); notify(t("Referral link copied", "Реферальная ссылка скопирована")); };
  const apply = async (event: FormEvent) => { event.preventDefault(); setError(null); try { const result = await api<PromoPreview>("/promo-codes/preview", { method: "POST", body: JSON.stringify({ code: promo }) }); setPreview(result); if (result.promo_type === "free_days") { await api("/promo-codes/redeem", { method: "POST", body: JSON.stringify({ code: result.code }) }); notify(t("Bonus days activated", "Бонусные дни активированы")); } } catch (value) { setPreview(null); setError(value instanceof Error ? value.message : "Promo failed"); } };
  if (!stats.data) return <ResourceState state={stats} />;
  const code = stats.data.code;
  return <div className="page-stack"><PageIntro eyebrow={t("Hazbit rewards", "Бонусы Hazbit")} title={t("Protection grows when shared", "Защита растёт, когда ею делятся")} text={t("Invite friends, earn secure days and activate private promo codes.", "Приглашайте друзей, получайте дни и активируйте персональные промокоды.")} />
    <section className="rewards-hero"><div><span className="eyebrow"><Gift size={14} /> {t("Your referral signal", "Ваш реферальный сигнал")}</span><h2>+{stats.data.granted_referrer_days}</h2><p>{t("bonus days earned", "бонусных дней получено")}</p><div className="referral-code"><span>{code?.code ?? "—"}</span><button onClick={() => code && copy(code.share_url)}><Copy size={15} /> {t("Copy link", "Скопировать ссылку")}</button></div></div><div className="reward-rings"><i /><i /><i /><span><UsersRound size={29} /><b>{stats.data.rewarded}</b><small>{t("rewarded", "награждено")}</small></span></div></section>
    <section className="reward-stats"><article><span>{t("Invited", "Приглашено")}</span><strong>{stats.data.total}</strong><small>{t("people opened your link", "перешли по вашей ссылке")}</small></article><article><span>{t("Pending", "Ожидают")}</span><strong>+{stats.data.pending_referrer_days}</strong><small>{t("days after qualification", "дней после подтверждения")}</small></article><article><span>{t("Conversion", "Конверсия")}</span><strong>{stats.data.total ? Math.round(stats.data.rewarded / stats.data.total * 100) : 0}%</strong><small>{t("became protected", "активировали защиту")}</small></article></section>
    <section className="surface-card promo-activate"><div><span className="promo-symbol"><Sparkles size={23} /></span><div><p className="eyebrow">{t("Have a code?", "Есть промокод?")}</p><h3>{t("Activate a private offer", "Активируйте персональное предложение")}</h3><p>{t("Try WELCOME20 for a payment discount or FAMILY7 for bonus days.", "Попробуйте WELCOME20 для скидки или FAMILY7 для бонусных дней.")}</p></div></div><form onSubmit={apply}><input value={promo} onChange={(event) => setPromo(event.target.value.toUpperCase())} placeholder={t("Enter promo code", "Введите промокод")} required minLength={3} /><button className="primary-button">{t("Check code", "Проверить код")}</button></form>{preview && <div className="promo-success"><BadgeCheck size={17} /><span><b>{preview.code}</b>{preview.promo_type === "free_days" ? `+${preview.value} ${t("days", "дней")}` : `−${preview.value}% · ${money(preview.final_amount_minor ?? 0, preview.currency ?? "RUB", locale)}`}</span></div>}{error && <div className="inline-error">{error}</div>}</section>
  </div>;
}

function SupportPage({ notify }: { notify: (value: string) => void }) {
  const { locale, t } = useI18n(); const tickets = useResource<Ticket[]>("/tickets"); const [selected, setSelected] = useState<Ticket | null>(null); const [creating, setCreating] = useState(false);
  return <div className="page-stack"><PageIntro eyebrow={t("Human support", "Поддержка людей")} title={t("We keep your signal clean", "Поможем восстановить стабильный сигнал")} text={t("Start a secure conversation. Your network context stays attached to the ticket.", "Создайте защищённый диалог. Контекст подключения останется внутри обращения.")} action={<button className="primary-button" onClick={() => setCreating(true)}><TicketPlus size={16} /> {t("New ticket", "Новое обращение")}</button>} />
    <section className="support-layout"><article className="support-promise"><span><Headphones size={25} /></span><p className="eyebrow">{t("Live operations", "Оперативная поддержка")}</p><h3>{t("Average reply", "Среднее время ответа")}</h3><strong>≈ 5 min</strong><p>{t("Connection incidents are automatically marked with higher priority.", "Проблемы подключения автоматически получают повышенный приоритет.")}</p><div><i className="live-dot" /> {t("Support team online", "Команда поддержки онлайн")}</div></article><section className="surface-card ticket-list-card"><header><div><p className="eyebrow">{t("Your conversations", "Ваши обращения")}</p><h3>{t("Support tickets", "Тикеты поддержки")}</h3></div><TicketCheck size={20} /></header>{tickets.data?.length ? <div className="customer-ticket-list">{tickets.data.map((ticket) => <button key={ticket.id} onClick={() => setSelected(ticket)}><span className={`ticket-mark ${ticket.status}`}><MessageCircle size={17} /></span><div><b>{ticket.subject}</b><small>#{ticket.public_number} · {relative(ticket.last_message_at, locale)}</small></div><Status value={ticket.status} /><ChevronRight size={16} /></button>)}</div> : <Empty icon={MessageCircle} text={t("No support conversations", "Обращений пока нет")} />}</section></section>
    {creating && <NewTicketDialog onClose={() => setCreating(false)} onDone={(ticket) => { setCreating(false); tickets.reload(); setSelected(ticket.ticket); notify(t("Ticket created", "Обращение создано")); }} />}{selected && <TicketDialog ticket={selected} onClose={() => setSelected(null)} onChanged={tickets.reload} />}
  </div>;
}

function NewTicketDialog({ onClose, onDone }: { onClose: () => void; onDone: (detail: TicketDetail) => void }) {
  const { t } = useI18n(); const [subject, setSubject] = useState(""); const [category, setCategory] = useState("connection"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { onDone(await api<TicketDetail>("/tickets", { method: "POST", headers: { "Idempotency-Key": idempotencyKey("ticket") }, body: JSON.stringify({ subject, category, message }) })); } catch (value) { setError(value instanceof Error ? value.message : "Unable to create ticket"); } finally { setBusy(false); } };
  return <Modal onClose={onClose} className="ticket-create-modal"><form onSubmit={submit}><div className="modal-heading"><span className="modal-icon"><TicketPlus size={20} /></span><div><p className="eyebrow">{t("Secure conversation", "Защищённый диалог")}</p><h2>{t("New support ticket", "Новое обращение")}</h2></div></div><label className="field">{t("Subject", "Тема")}<input value={subject} onChange={(event) => setSubject(event.target.value)} minLength={3} required /></label><label className="field">{t("Category", "Категория")}<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="connection">{t("Connection", "Подключение")}</option><option value="payment">{t("Payment", "Оплата")}</option><option value="subscription">{t("Subscription", "Подписка")}</option><option value="account">{t("Account", "Аккаунт")}</option><option value="other">{t("Other", "Другое")}</option></select></label><label className="field">{t("What happened?", "Что произошло?")}<textarea value={message} onChange={(event) => setMessage(event.target.value)} minLength={1} maxLength={5000} required /></label>{error && <div className="inline-error">{error}</div>}<button className="primary-button wide" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Send size={16} />} {t("Send securely", "Отправить безопасно")}</button></form></Modal>;
}

function TicketDialog({ ticket, onClose, onChanged }: { ticket: Ticket; onClose: () => void; onChanged: () => void }) {
  const { locale, t } = useI18n(); const detail = useResource<TicketDetail>(`/tickets/${ticket.id}`); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const send = async (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; setBusy(true); try { await api(`/tickets/${ticket.id}/messages`, { method: "POST", headers: { "Idempotency-Key": idempotencyKey("ticket-message") }, body: JSON.stringify({ body: message }) }); setMessage(""); detail.reload(); onChanged(); } finally { setBusy(false); } };
  return <Modal onClose={onClose} className="conversation-modal"><header><div><p className="eyebrow">{t("Ticket", "Тикет")} #{ticket.public_number}</p><h2>{ticket.subject}</h2><div className="ticket-meta"><Status value={detail.data?.ticket.status ?? ticket.status} /><span>{t("Opened", "Создан")} {date(ticket.created_at, locale)}</span></div></div><button className="icon-button" onClick={onClose}><X size={17} /></button></header><div className="conversation-messages">{detail.loading ? <LoaderCircle className="spin" /> : detail.data?.messages.map((item) => <article className={item.sender_user_id ? "mine" : "support"} key={item.id}><span>{item.sender_user_id ? t("You", "Вы") : "Hazbit Support"}<small>{relative(item.created_at, locale)}</small></span><p>{item.body}</p></article>)}</div>{ticket.status !== "closed" && <form className="customer-composer" onSubmit={send}><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder={t("Write a reply…", "Напишите ответ…")} required /><button disabled={busy || !message.trim()}>{busy ? <LoaderCircle className="spin" size={17} /> : <Send size={17} />}</button></form>}</Modal>;
}

function ProfilePage({ overview, theme, setTheme, onLogout }: { overview: Overview | null; theme: Theme; setTheme: (theme: Theme) => void; onLogout: () => void }) {
  const { locale, setLocale, t } = useI18n(); const user = overview?.user;
  return <div className="page-stack"><PageIntro eyebrow={t("Account & preferences", "Аккаунт и настройки")} title={t("Your Hazbit identity", "Ваш профиль Hazbit")} text={t("Manage how this device looks and review linked identity channels.", "Настройте отображение и проверьте привязанные способы входа.")} />
    <section className="profile-grid"><article className="surface-card identity-profile"><span className="large-avatar">{initials(user?.public_name ?? user?.email ?? "H")}</span><h3>{user?.public_name ?? t("Hazbit user", "Пользователь Hazbit")}</h3><p>{user?.email}</p><Status value="verified" /><div><span><Mail size={15} /> Email<b>{user?.email}</b></span><span><MessageCircle size={15} /> Telegram<b>{user?.telegram_username ? `@${user.telegram_username}` : t("Not linked", "Не привязан")}</b></span><span><CalendarDays size={15} /> {t("Member since", "С нами с")}<b>{date(user?.created_at ?? null, locale)}</b></span></div></article>
      <div className="settings-column"><section className="surface-card preference-card"><header><div><p className="eyebrow">{t("Appearance", "Внешний вид")}</p><h3>{t("Make Hazbit yours", "Настройте Hazbit под себя")}</h3></div><Sun size={20} /></header><div className="setting-row"><span><Moon size={17} /><span><b>{t("Theme", "Тема")}</b><small>{t("Comfortable in any light", "Комфортно при любом освещении")}</small></span></span><div className="choice"><button className={theme === "dark" ? "active" : ""} onClick={() => setTheme("dark")}>{t("Dark", "Тёмная")}</button><button className={theme === "light" ? "active" : ""} onClick={() => setTheme("light")}>{t("Light", "Светлая")}</button></div></div><div className="setting-row"><span><Languages size={17} /><span><b>{t("Language", "Язык")}</b><small>{t("Interface and notifications", "Интерфейс и уведомления")}</small></span></span><div className="choice"><button className={locale === "ru" ? "active" : ""} onClick={() => setLocale("ru")}>RU</button><button className={locale === "en" ? "active" : ""} onClick={() => setLocale("en")}>EN</button></div></div></section>
        <section className="surface-card security-card"><header><div><p className="eyebrow">{t("Account security", "Безопасность аккаунта")}</p><h3>{t("Session protection", "Защита сессии")}</h3></div><LockKeyhole size={20} /></header><div className="security-line"><BadgeCheck size={17} /><span><b>{t("Passwordless sign-in", "Вход без пароля")}</b><small>{t("Email OTP and rotating refresh tokens", "Email OTP и ротация refresh-токенов")}</small></span><Status value="active" /></div><div className="security-line"><ShieldCheck size={17} /><span><b>{t("This device", "Это устройство")}</b><small>{t("Fingerprint and IP changes are audited", "Изменения fingerprint и IP фиксируются")}</small></span><Status value="trusted" /></div><button className="logout-button" onClick={onLogout}><LogOut size={16} /> {t("Sign out on this device", "Выйти на этом устройстве")}</button></section></div>
    </section>
  </div>;
}

function Brand() { return <div className="brand"><span className="brand-mark"><i /><i /><i /></span><span>HAZBIT<small>PRIVATE NETWORK</small></span></div>; }
function PageIntro({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: ReactNode }) { return <section className="page-intro"><div><p>{eyebrow}</p><h2>{title}</h2><span>{text}</span></div>{action}</section>; }
function SignalOrb({ connected }: { connected: boolean }) { return <div className={`signal-orb ${connected ? "connected" : ""}`} aria-label={connected ? "Connected" : "Disconnected"}><i /><i /><i /><span>{connected ? <ShieldCheck size={35} /> : <WifiOff size={35} />}</span></div>; }
function DeviceIcon({ platform }: { platform: string | null }) { return platform?.toLowerCase().includes("tv") ? <Router size={23} /> : platform?.toLowerCase().includes("mac") || platform?.toLowerCase().includes("window") ? <MonitorSmartphone size={23} /> : <Smartphone size={23} />; }
function Status({ value }: { value: string }) { const { t } = useI18n(); const label: Record<string, [string, string]> = { active: ["Active", "Активен"], pending: ["Pending", "Ожидает"], pending_upload: ["Awaiting receipt", "Ждёт чек"], analyzing: ["Analyzing", "Проверяется"], approved: ["Approved", "Подтверждён"], activated: ["Activated", "Активирован"], waiting_user: ["Waiting for you", "Ждёт вас"], open: ["Open", "Открыт"], in_progress: ["In progress", "В работе"], closed: ["Closed", "Закрыт"], verified: ["Verified", "Подтверждён"], trusted: ["Trusted", "Доверенное"], inactive: ["Inactive", "Неактивен"] }; const copy = label[value] ?? [titleCase(value), titleCase(value)]; return <span className={`status ${value}`}><i /> {t(copy[0], copy[1])}</span>; }
function Empty({ icon: Icon, text }: { icon: LucideIcon; text: string }) { return <div className="empty-state"><Icon size={24} /><span>{text}</span></div>; }
function ResourceState({ state }: { state: LoadState<unknown> }) { const { t } = useI18n(); return <div className="resource-state">{state.loading ? <><LoaderCircle className="spin" size={22} /><span>{t("Loading your secure space…", "Загружаем защищённое пространство…")}</span></> : <><CircleHelp size={22} /><span>{state.error ?? t("Nothing here yet", "Здесь пока ничего нет")}</span></>}</div>; }
function Modal({ children, onClose, className = "" }: { children: ReactNode; onClose: () => void; className?: string }) { const { t } = useI18n(); return <div className="modal-layer"><button className="modal-scrim" onClick={onClose} aria-label={t("Close dialog", "Закрыть окно")} /><section className={`modal ${className}`}><button className="modal-close icon-button" onClick={onClose} aria-label={t("Close", "Закрыть")}><X size={17} /></button>{children}</section></div>; }

const initials = (value: string) => value.split(/[\s@._-]+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "HZ";
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const shortId = (value: string) => value.length > 13 ? `${value.slice(0, 8)}…${value.slice(-4)}` : value;
const date = (value: string | null, locale: Locale) => value ? new Date(value).toLocaleDateString(locale === "ru" ? "ru-RU" : "en-US", { day: "numeric", month: "short", year: "numeric" }) : "—";
const relative = (value: string, locale: Locale) => { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60_000)); if (locale === "ru") return minutes < 60 ? `${minutes} мин. назад` : minutes < 1440 ? `${Math.round(minutes / 60)} ч назад` : `${Math.round(minutes / 1440)} дн. назад`; return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago`; };
const money = (amount: number, currency: string, locale: Locale) => new Intl.NumberFormat(locale === "ru" ? "ru-RU" : "en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount / 100);
const greeting = (locale: Locale, name: string) => { const hour = new Date().getHours(); if (locale === "ru") return `${hour < 12 ? "Доброе утро" : hour < 18 ? "Добрый день" : "Добрый вечер"}, ${name}`; return `${hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"}, ${name}`; };
