import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import {
  ArrowLeft, ArrowRight, BadgeCheck, Bell, Bitcoin, Check, ChevronRight, CircleHelp, Copy, CreditCard, Crown,
  Gift, Globe2, Headphones, Home, Languages, Link2, LoaderCircle, LockKeyhole, MessageCircle,
  Landmark, MonitorSmartphone, Moon, MoreHorizontal, Plus, QrCode, Send, ShieldCheck, Smartphone, Sparkles, Sun,
  TicketCheck, Trash2, UserPlus, UsersRound, WalletCards, Wifi, X, Zap, type LucideIcon,
} from "lucide-react";
import { api, authenticateTelegram, demoMode, hasSession, key, type Device, type FamilyGroup, type Overview, type Plan, type PromoPreview, type ReferralStatistics, type Ticket, type TicketDetail, type Wallet, type WalletPurchase, type WalletTopUp } from "./api";
import { MiniBrand } from "./components/MiniBrand";
import { TelegramHome } from "./features/home/TelegramHome";
import { TelegramLaunch } from "./features/launch/TelegramLaunch";
import { tg } from "./telegram";
import "./features/experience.css";

type Locale = "ru" | "en";
type Theme = "dark" | "light";
type Tab = "home" | "plans" | "devices" | "family" | "more";
interface Load<T> { data: T | null; loading: boolean; error: string | null; reload: () => void; setData: (value: T) => void }

const nav: Array<{ id: Tab; icon: LucideIcon; en: string; ru: string }> = [
  { id: "home", icon: Home, en: "Home", ru: "Главная" },
  { id: "plans", icon: Crown, en: "Plans", ru: "Тарифы" },
  { id: "devices", icon: MonitorSmartphone, en: "Devices", ru: "Устройства" },
  { id: "family", icon: UsersRound, en: "Family", ru: "Семья" },
  { id: "more", icon: MoreHorizontal, en: "More", ru: "Ещё" },
];

function useResource<T>(path: string, enabled = true): Load<T> {
  const [revision, setRevision] = useState(0); const [state, setState] = useState<Omit<Load<T>, "reload" | "setData">>({ data: null, loading: enabled, error: null });
  useEffect(() => { if (!enabled) return; let active = true; setState((value) => ({ ...value, loading: true, error: null })); api<T>(path).then((data) => active && setState({ data, loading: false, error: null })).catch((error: unknown) => active && setState({ data: null, loading: false, error: error instanceof Error ? error.message : "Request failed" })); return () => { active = false; }; }, [path, revision, enabled]);
  return { ...state, reload: () => setRevision((value) => value + 1), setData: (data) => setState({ data, loading: false, error: null }) };
}

export default function App() {
  const [ready, setReady] = useState(hasSession()); const [error, setError] = useState<string | null>(null);
  const [locale, setLocale] = useState<Locale>(() => {
    const stored = localStorage.getItem("hazbit-tma-locale");
    if (stored === "ru" || stored === "en") return stored;
    return tg.user?.language_code?.startsWith("en") ? "en" : "ru";
  });
  const [theme, setTheme] = useState<Theme>(() => localStorage.getItem("hazbit-tma-theme") === "light" ? "light" : "dark");
  const [tab, setTab] = useState<Tab>(() => routeFromStart(tg.startParam)); const [overlay, setOverlay] = useState<ReactNode | null>(null); const [toast, setToast] = useState<string | null>(null);
  const tr = useCallback((en: string, ru: string) => locale === "ru" ? ru : en, [locale]);
  const overview = useResource<Overview>("/portal/overview", ready);
  const wallet = useResource<Wallet>("/billing/wallet", ready);

  useEffect(() => tg.boot(), []);
  useEffect(() => { localStorage.setItem("hazbit-tma-locale", locale); document.documentElement.lang = locale; }, [locale]);
  useEffect(() => { localStorage.setItem("hazbit-tma-theme", theme); document.documentElement.dataset.theme = theme; tg.appearance(theme); }, [theme]);
  useEffect(() => { if (ready) return; authenticateTelegram().then(async () => { setReady(true); const start = tg.startParam; if (start?.startsWith("invite_")) { await api("/family/invitations/accept", { method: "POST", body: JSON.stringify({ token: start.slice(7) }) }); setTab("family"); setToast(tr("Family invitation accepted", "Приглашение в семью принято")); } }).catch((value: unknown) => setError(value instanceof Error ? value.message : tr("Telegram authentication failed", "Не удалось войти через Telegram"))); }, [ready, tr]);
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(null), 2400); return () => window.clearTimeout(id); }, [toast]);
  useEffect(() => tg.back(overlay ? () => setOverlay(null) : null), [overlay]);

  const go = (next: Tab) => { tg.haptic("selection"); setTab(next); setOverlay(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  if (!ready) return <TelegramLaunch error={error} retry={() => { setError(null); void authenticateTelegram().then(() => setReady(true)).catch((value: unknown) => setError(value instanceof Error ? value.message : tr("Authentication failed", "Не удалось выполнить вход"))); }} tr={tr} />;
  if (!overview.data) return <TelegramLaunch error={overview.error} tr={tr} />;
  const data = overview.data;
  const notify = (message: string) => { tg.haptic("success"); setToast(message); };
  const walletSheet = () => setOverlay(<WalletSheet tr={tr} notify={notify} close={() => setOverlay(null)} changed={wallet.reload} />);
  const screen = tab === "home" ? <TelegramHome overview={data} wallet={wallet.data} displayName={data.user.public_name ?? tg.user?.first_name ?? "Hazbit"} tr={tr} go={go} notify={notify} onWallet={walletSheet} />
    : tab === "plans" ? <PlansScreen current={data.subscription?.plan_slug ?? null} tr={tr} notify={notify} open={setOverlay} onChanged={() => { wallet.reload(); overview.reload(); }} />
    : tab === "devices" ? <DevicesScreen overview={data} tr={tr} notify={notify} open={setOverlay} />
    : tab === "family" ? <FamilyScreen identity={data.user.id} tr={tr} notify={notify} open={setOverlay} />
    : <MoreScreen overview={data} locale={locale} setLocale={setLocale} theme={theme} setTheme={setTheme} tr={tr} notify={notify} open={setOverlay} />;

  return <div className="tma-frame"><header className="tma-header"><MiniBrand /><div className="header-actions">{demoMode && <span className="demo"><Sparkles size={11} /> DEMO</span>}<button aria-label={theme === "dark" ? tr("Switch to light theme", "Включить светлую тему") : tr("Switch to dark theme", "Включить тёмную тему")} onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>{theme === "dark" ? <Sun size={18} /> : <Moon size={18} />}</button><button className="notification-control" aria-label={tr("Notifications", "Уведомления")} onClick={() => setToast(tr("No new notifications", "Новых уведомлений нет"))}><Bell size={18} /><i /></button><span className="avatar">{initials(data.user.public_name ?? tg.user?.first_name ?? "H")}</span></div></header><main className="tma-content">{screen}</main><nav className="tma-dock" aria-label={tr("Mini App navigation", "Навигация Mini App")}>{nav.map(({ id, icon: Icon, en, ru }) => <button key={id} className={tab === id ? "active" : ""} onClick={() => go(id)}><Icon size={20} /><span>{tr(en, ru)}</span>{id === "more" && data.open_ticket_count > 0 && <i />}</button>)}</nav>{overlay}{toast && <div className="tma-toast"><Check size={15} />{toast}</div>}</div>;
}

function PlansScreen({ current, tr, notify, open, onChanged }: { current: string | null; tr: Tr; notify: Notify; open: Open; onChanged: () => void }) {
  const plans = useResource<Plan[]>("/portal/plans"); const deepLink = tg.startParam; const requestedPlan = deepLink?.startsWith("plan_") ? deepLink.slice(5) : null; const [promo, setPromo] = useState(deepLink?.startsWith("promo_") ? deepLink.slice(6).toUpperCase() : ""); const [preview, setPreview] = useState<PromoPreview | null>(null); const [checking, setChecking] = useState(false);
  const orderedPlans = useMemo(() => plans.data ? [...plans.data].sort((left, right) => Number(right.slug === requestedPlan) - Number(left.slug === requestedPlan)) : null, [plans.data, requestedPlan]);
  const checkPromo = async (event: FormEvent) => { event.preventDefault(); setChecking(true); try { const value = await api<PromoPreview>("/promo-codes/preview", { method: "POST", body: JSON.stringify({ code: promo }) }); setPreview(value); notify(tr("Promo code applied", "Промокод применён")); } finally { setChecking(false); } };
  return <div className="screen-stack"><ScreenTitle eyebrow={tr("Choose access", "Выберите доступ")} title={tr("Protection that fits", "Защита под ваши задачи")} text={tr("Change the plan without losing devices or remaining days.", "Меняйте тариф без потери устройств и оставшихся дней.")} />{!orderedPlans ? <State loading={plans.loading} error={plans.error} tr={tr} /> : <section className="tma-plans">{orderedPlans.map((plan) => { const price = plan.prices[0]; const active = plan.slug === current; return <article key={plan.id} className={`${plan.slug} ${active ? "active" : ""}`}><header><span>{plan.slug === "family" ? <UsersRound /> : plan.slug === "premium" ? <Crown /> : <ShieldCheck />}</span>{active && <em><BadgeCheck size={12} /> {tr("Current", "Текущий")}</em>}</header><h3>{plan.name}</h3><p>{plan.slug === "family" ? tr("For the people closest to you.", "Для самых близких людей.") : plan.slug === "premium" ? tr("More devices and priority routes.", "Больше устройств и приоритетные маршруты.") : tr("Simple private access.", "Простой приватный доступ.")}</p><div className="tma-price"><b>{money(price.amount_minor, price.currency)}</b><small>/ {tr("month", "месяц")}</small></div><ul><li><Check />{plan.device_limit} {tr("devices", "устройств")}</li><li><Check />{plan.family_member_limit || 1} {tr("people", "участников")}</li></ul><button disabled={active} onClick={() => open(<PurchaseSheet plan={plan} tr={tr} notify={notify} close={() => open(null)} open={open} onChanged={onChanged} />)}>{active ? tr("Active", "Активен") : tr("Choose", "Выбрать")}<ArrowRight size={15} /></button></article>; })}</section>}<form className="promo-bar" onSubmit={checkPromo}><span><Gift size={18} /><input value={promo} onChange={(event) => setPromo(event.target.value.toUpperCase())} placeholder={tr("Promo code", "Промокод")} required /></span><button disabled={checking}>{checking ? <LoaderCircle className="spin" size={15} /> : tr("Apply", "Применить")}</button></form>{preview && <div className="promo-result"><Sparkles size={16} /><b>{preview.code}</b><span>−{preview.value}%</span></div>}</div>;
}

function PurchaseSheet({ plan, tr, notify, close, open, onChanged }: { plan: Plan; tr: Tr; notify: Notify; close: () => void; open: Open; onChanged: () => void }) {
  const price = plan.prices[0]; const wallet = useResource<Wallet>("/billing/wallet"); const [autoRenew, setAutoRenew] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const enough = (wallet.data?.balance_minor ?? 0) >= price.amount_minor;
  const buy = useCallback(async () => { setBusy(true); setError(null); try { await api<WalletPurchase>("/billing/purchases", { method: "POST", headers: { "Idempotency-Key": key("tma-wallet-purchase") }, body: JSON.stringify({ plan_price_id: price.id, auto_renew: autoRenew }) }); notify(tr("Plan paid from balance", "Тариф оплачен с баланса")); onChanged(); close(); } catch (value) { setError(value instanceof Error ? value.message : tr("Payment failed", "Не удалось оплатить")); tg.haptic("error"); } finally { setBusy(false); } }, [autoRenew, close, notify, onChanged, price.id, tr]);
  useEffect(() => tg.main(tr(`Pay ${money(price.amount_minor, price.currency)}`, `Оплатить ${money(price.amount_minor, price.currency)}`), buy, busy), [buy, busy, price.amount_minor, price.currency, tr]);
  const openWallet = () => open(<WalletSheet tr={tr} notify={notify} close={() => open(null)} changed={onChanged} />);
  return <Sheet close={close}><div className="sheet-symbol"><WalletCards size={23} /></div><p className="eyebrow">{tr("HAZBIT BALANCE", "БАЛАНС HAZBIT")}</p><h2>{plan.name}</h2><p>{tr("The tariff is paid from your Hazbit balance. Top it up securely through Platega when needed.", "Тариф оплачивается с баланса Hazbit. При необходимости пополните его через защищённую страницу Platega.")}</p><div className="invoice-summary"><span>{tr("Plan", "Тариф")}<b>{plan.name}</b></span><span>{tr("Available", "Доступно")}<b>{wallet.data ? money(wallet.data.balance_minor, wallet.data.currency) : "…"}</b></span><strong>{tr("To be charged", "К списанию")}<b>{money(price.amount_minor, price.currency)}</b></strong></div><label className="tma-renew"><input type="checkbox" checked={autoRenew} onChange={(event) => setAutoRenew(event.target.checked)} /><span><b>{tr("Automatic renewal", "Автопродление")}</b><small>{tr("Only from the Hazbit balance", "Только с баланса Hazbit")}</small></span></label>{error && <div className="sheet-error">{error}</div>}{!wallet.loading && !enough ? <button className="sheet-primary" onClick={openWallet}><WalletCards size={17} /> {tr("Top up balance", "Пополнить баланс")}</button> : <button className="sheet-primary" disabled={busy || wallet.loading} onClick={buy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Check size={17} />} {tr("Pay from balance", "Оплатить с баланса")}</button>}</Sheet>;
}

function WalletSheet({ tr, notify, close, changed }: { tr: Tr; notify: Notify; close: () => void; changed: () => void }) {
  const wallet = useResource<Wallet>("/billing/wallet"); const [amount, setAmount] = useState("1000"); const [method, setMethod] = useState<2 | 10 | 13>(2); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const topUp = async (event: FormEvent) => { event.preventDefault(); const rubles = Number(amount); if (!Number.isInteger(rubles) || rubles < 100) { setError(tr("Enter a whole amount from 100 ₽", "Введите целую сумму от 100 ₽")); return; } setBusy(true); setError(null); try { const topUp = await api<WalletTopUp>("/billing/top-ups", { method: "POST", headers: { "Idempotency-Key": key("tma-top-up") }, body: JSON.stringify({ amount_minor: rubles * 100, currency: "RUB", payment_method: method }) }); if (topUp.checkout_url) { tg.openLink(topUp.checkout_url); notify(tr("Platega checkout opened", "Открыта форма Platega")); close(); return; } wallet.reload(); changed(); notify(tr("Balance topped up", "Баланс пополнен")); } catch (value) { setError(value instanceof Error ? value.message : tr("Top-up failed", "Не удалось пополнить баланс")); tg.haptic("error"); } finally { setBusy(false); } };
  const toggleRenew = async () => { if (!wallet.data) return; setBusy(true); setError(null); try { const value = await api<Wallet>("/billing/auto-renew", { method: "PATCH", body: JSON.stringify({ enabled: !wallet.data.auto_renew_enabled }) }); wallet.setData(value); changed(); notify(value.auto_renew_enabled ? tr("Auto-renewal enabled", "Автопродление включено") : tr("Auto-renewal disabled", "Автопродление выключено")); } catch (value) { setError(value instanceof Error ? value.message : tr("Unable to update", "Не удалось изменить настройку")); } finally { setBusy(false); } };
  const methods = [{ id: 2 as const, icon: Landmark, label: tr("SBP", "СБП") }, { id: 10 as const, icon: CreditCard, label: tr("Card", "Карта") }, { id: 13 as const, icon: Bitcoin, label: tr("Crypto", "Крипто") }];
  return <Sheet close={close} className="wallet-sheet"><div className="tma-wallet-head"><span><WalletCards /></span><small>{tr("AVAILABLE BALANCE", "ДОСТУПНЫЙ БАЛАНС")}</small><strong>{wallet.data ? money(wallet.data.balance_minor, wallet.data.currency) : "…"}</strong><p>{tr("Top up via Platega. Bank details are never stored in Hazbit.", "Пополнение через Platega. Банковские данные не хранятся в Hazbit.")}</p></div><form onSubmit={topUp}><label>{tr("Top-up amount", "Сумма пополнения")}<span className="tma-amount"><input inputMode="numeric" value={amount} onChange={(event) => setAmount(event.target.value.replace(/\D/g, "").slice(0, 7))} required /><b>₽</b></span></label><fieldset><legend>{tr("Payment method", "Способ оплаты")}</legend><div className="tma-methods">{methods.map(({ id, icon: Icon, label }) => <button type="button" key={id} className={method === id ? "active" : ""} onClick={() => setMethod(id)}><Icon /><span>{label}</span></button>)}</div></fieldset>{error && <div className="sheet-error" role="alert">{error}</div>}<button className="sheet-primary" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <ArrowRight />} {tr("Continue in Platega", "Перейти в Platega")}</button></form><button className={`tma-auto-renew ${wallet.data?.auto_renew_enabled ? "active" : ""}`} disabled={busy || !wallet.data?.auto_renew_plan_price_id} onClick={toggleRenew}><span><ShieldCheck /><span><b>{tr("Automatic renewal", "Автопродление")}</b><small>{wallet.data?.auto_renew_enabled ? tr("Enabled", "Включено") : tr("Enable after buying a plan", "Включите после покупки тарифа")}</small></span></span><i /></button></Sheet>;
}

function DevicesScreen({ overview, tr, notify, open }: { overview: Overview; tr: Tr; notify: Notify; open: Open }) {
  const devices = useResource<Device[]>("/devices"); const remove = async (device: Device) => { await api(`/devices/${device.id}`, { method: "DELETE" }); devices.reload(); notify(tr("Device removed", "Устройство удалено")); };
  return <div className="screen-stack"><ScreenTitle eyebrow={tr("Private perimeter", "Приватный периметр")} title={tr("Your devices", "Ваши устройства")} text={`${devices.data?.length ?? 0} / ${overview.subscription?.device_limit ?? 0} ${tr("slots in use", "слотов занято")}`} action={<button className="round-add" onClick={() => open(<AddDeviceSheet tr={tr} close={() => open(null)} done={() => { open(null); devices.reload(); notify(tr("Device reserved", "Устройство добавлено")); }} />)}><Plus size={19} /></button>} /><div className="slot-meter">{Array.from({ length: overview.subscription?.device_limit ?? 0 }, (_, index) => <i className={index < (devices.data?.length ?? 0) ? "used" : ""} key={index} />)}</div>{!devices.data ? <State loading={devices.loading} error={devices.error} tr={tr} /> : <section className="device-list">{devices.data.map((device) => <article key={device.id}><span className="device-glyph">{device.platform?.includes("mac") ? <MonitorSmartphone /> : <Smartphone />}</span><div><b>{device.label}</b><small>{device.platform} · {device.status === "active" ? tr("Connected", "Подключено") : tr("Provisioning", "Подключается")}</small></div><button aria-label={tr(`Remove ${device.label}`, `Удалить ${device.label}`)} onClick={() => remove(device)}><Trash2 size={15} /></button></article>)}</section>}<button className="setup-card" onClick={() => copySetup(notify, tr)}><span><QrCode size={23} /></span><div><b>{tr("Private setup link", "Приватная ссылка настройки")}</b><small>{tr("Copy once, then open in your VPN app", "Скопируйте и откройте в VPN-приложении")}</small></div><Copy size={17} /></button></div>;
}

function AddDeviceSheet({ tr, close, done }: { tr: Tr; close: () => void; done: () => void }) {
  const [label, setLabel] = useState(""); const [platform, setPlatform] = useState("iOS"); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api("/devices", { method: "POST", headers: { "Idempotency-Key": key("tma-device") }, body: JSON.stringify({ label, platform, hwid: crypto.randomUUID().replaceAll("-", "").slice(0, 24), os_version: "unknown", device_model: label }) }); done(); } finally { setBusy(false); } };
  return <Sheet close={close}><form onSubmit={submit}><div className="sheet-symbol"><Smartphone size={22} /></div><p className="eyebrow">{tr("NEW SECURE SLOT", "НОВОЕ ЗАЩИЩЁННОЕ УСТРОЙСТВО")}</p><h2>{tr("Add a device", "Добавить устройство")}</h2><label>{tr("Device name", "Название устройства")}<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder={tr("My iPhone", "Мой iPhone")} required /></label><label>{tr("Platform", "Платформа")}<select value={platform} onChange={(event) => setPlatform(event.target.value)}><option>iOS</option><option>Android</option><option>macOS</option><option>Windows</option><option>Linux</option></select></label><button className="sheet-primary" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <Plus size={17} />} {tr("Reserve slot", "Зарезервировать слот")}</button></form></Sheet>;
}

function FamilyScreen({ identity, tr, notify, open }: { identity: string; tr: Tr; notify: Notify; open: Open }) {
  const family = useResource<FamilyGroup>("/family/group"); const group = family.data; if (!group) return <State loading={family.loading} error={family.error} tr={tr} />; const owner = group.owner_user_id === identity;
  return <div className="screen-stack"><section className="family-card"><div className="family-cloud"><span>A</span><i>T</i><i>S</i><b><ShieldCheck size={23} /></b></div><p className="eyebrow">{tr("FAMILY SHIELD", "СЕМЕЙНАЯ ЗАЩИТА")}</p><h1>{group.name}</h1><p>{tr("Separate accounts. One private perimeter.", "Отдельные аккаунты. Один приватный периметр.")}</p></section><section className="family-capacity"><div><small>{tr("People", "Участники")}</small><b>{group.active_member_count} / {group.member_limit}</b></div><span /><div><small>{tr("Devices", "Устройства")}</small><b>{group.active_device_count} / {group.device_limit}</b></div></section><section className="member-list"><header><h3>{tr("Protected people", "Защищённые участники")}</h3>{owner && <button onClick={() => open(<InviteSheet group={group} tr={tr} close={() => open(null)} done={() => { open(null); family.reload(); notify(tr("Invitation sent", "Приглашение создано")); }} />)}><UserPlus size={16} />{tr("Invite", "Пригласить")}</button>}</header>{group.members.map((member) => <article key={member.id}><span>{initials(member.email ?? "H")}</span><div><b>{member.email}</b><small>{member.role === "owner" ? tr("Owner", "Владелец") : tr("Member", "Участник")}</small></div>{member.role === "owner" && <Crown size={15} />}</article>)}</section>{group.invitations.filter((item) => item.status === "pending").length > 0 && <section className="pending-card"><small>{tr("Waiting for acceptance", "Ожидают принятия")}</small>{group.invitations.filter((item) => item.status === "pending").map((item) => <div key={item.id}><MessageCircle size={15} /><b>{item.invited_email}</b><span>{tr("Sent", "Отправлено")}</span></div>)}</section>}</div>;
}

function InviteSheet({ group, tr, close, done }: { group: FamilyGroup; tr: Tr; close: () => void; done: () => void }) {
  const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api(`/family/groups/${group.id}/invitations`, { method: "POST", body: JSON.stringify({ invited_email: email }) }); done(); } finally { setBusy(false); } };
  return <Sheet close={close}><form onSubmit={submit}><div className="sheet-symbol"><UserPlus size={22} /></div><p className="eyebrow">{tr("FAMILY INVITE", "СЕМЕЙНОЕ ПРИГЛАШЕНИЕ")}</p><h2>{tr("Share protection", "Поделиться защитой")}</h2><p>{tr("The person will receive a private link and keep a separate Hazbit account.", "Человек получит приватную ссылку и сохранит отдельный аккаунт Hazbit.")}</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="person@example.com" required /></label><button className="sheet-primary" disabled={busy}><Send size={17} /> {tr("Create invitation", "Создать приглашение")}</button></form></Sheet>;
}

function MoreScreen({ overview, locale, setLocale, theme, setTheme, tr, notify, open }: { overview: Overview; locale: Locale; setLocale: (locale: Locale) => void; theme: Theme; setTheme: (theme: Theme) => void; tr: Tr; notify: Notify; open: Open }) {
  const rewards = useResource<ReferralStatistics>("/referrals/statistics"); const tickets = useResource<Ticket[]>("/tickets"); const share = () => { const url = rewards.data?.code?.share_url; if (url) tg.openTelegram(`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(tr("Join my private Hazbit network", "Присоединяйся к моей приватной сети Hazbit"))}`); };
  useEffect(() => { const start = tg.startParam; if (!start?.startsWith("ticket_") || !tickets.data) return; const target = start.slice(7); const ticket = tickets.data.find((item) => item.id === target || String(item.public_number) === target); if (ticket) open(<TicketSheet ticket={ticket} tr={tr} close={() => open(null)} />); }, [tickets.data]);
  return <div className="screen-stack"><ScreenTitle eyebrow={tr("Your Hazbit", "Ваш Hazbit")} title={tr("More control", "Больше возможностей")} text={tr("Rewards, support and Mini App preferences.", "Бонусы, поддержка и настройки Mini App.")} /><section className="reward-card"><span><Gift size={24} /></span><div><small>{tr("Bonus days", "Бонусные дни")}</small><h3>+{rewards.data?.granted_referrer_days ?? 0}</h3><p>{rewards.data?.code?.code ?? "—"}</p></div><button onClick={share}><Send size={16} />{tr("Share", "Поделиться")}</button></section><section className="more-section"><header><h3>{tr("Support", "Поддержка")}</h3><span>{overview.open_ticket_count}</span></header>{tickets.data?.map((ticket) => <button className="ticket-row" key={ticket.id} onClick={() => open(<TicketSheet ticket={ticket} tr={tr} close={() => open(null)} />)}><span><MessageCircle size={17} /></span><div><b>{ticket.subject}</b><small>#{ticket.public_number} · {status(ticket.status, tr)}</small></div><ChevronRight size={16} /></button>)}</section><section className="more-section settings"><header><h3>{tr("Mini App settings", "Настройки Mini App")}</h3></header><div className="setting"><span>{theme === "dark" ? <Moon size={18} /> : <Sun size={18} />}<div><b>{tr("Appearance", "Оформление")}</b><small>{theme === "dark" ? tr("Dark theme", "Тёмная тема") : tr("Light theme", "Светлая тема")}</small></div></span><div className="lang-choice theme-choice"><button className={theme === "dark" ? "active" : ""} onClick={() => setTheme("dark")}>{tr("Dark", "Тёмная")}</button><button className={theme === "light" ? "active" : ""} onClick={() => setTheme("light")}>{tr("Light", "Светлая")}</button></div></div><div className="setting"><span><Languages size={18} /><div><b>{tr("Language", "Язык")}</b><small>{tr("Interface language", "Язык интерфейса")}</small></div></span><div className="lang-choice"><button className={locale === "ru" ? "active" : ""} onClick={() => setLocale("ru")}>RU</button><button className={locale === "en" ? "active" : ""} onClick={() => setLocale("en")}>EN</button></div></div><div className="setting"><span><LockKeyhole size={18} /><div><b>{tr("Telegram session", "Telegram-сессия")}</b><small>{tr("Signed initData and rotating JWT", "Подписанный initData и ротация JWT")}</small></div></span><BadgeCheck className="verified" size={18} /></div></section><section className="telegram-profile"><span className="large-avatar">{initials(overview.user.public_name ?? tg.user?.first_name ?? "H")}</span><div><b>{overview.user.public_name ?? tg.user?.first_name}</b><small>{overview.user.telegram_username ? `@${overview.user.telegram_username}` : `Telegram ID ${overview.user.telegram_user_id ?? "—"}`}</small></div><ShieldCheck size={19} /></section></div>;
}

function TicketSheet({ ticket, tr, close }: { ticket: Ticket; tr: Tr; close: () => void }) {
  const detail = useResource<TicketDetail>(`/tickets/${ticket.id}`); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const send = async (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; setBusy(true); try { await api(`/tickets/${ticket.id}/messages`, { method: "POST", headers: { "Idempotency-Key": key("tma-ticket") }, body: JSON.stringify({ body: message }) }); setMessage(""); detail.reload(); tg.haptic("success"); } finally { setBusy(false); } };
  return <Sheet close={close} className="chat-sheet"><header className="chat-head"><button onClick={close}><ArrowLeft size={18} /></button><div><small>{tr("Ticket", "Тикет")} #{ticket.public_number}</small><b>{ticket.subject}</b></div><span className="online" /></header><div className="chat-messages">{detail.loading ? <LoaderCircle className="spin" /> : detail.data?.messages.map((item) => <article className={item.sender_user_id ? "mine" : "support"} key={item.id}><small>{item.sender_user_id ? tr("You", "Вы") : "Hazbit Support"}</small><p>{item.body}</p></article>)}</div>{ticket.status !== "closed" && <form className="chat-composer" onSubmit={send}><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder={tr("Write a reply…", "Напишите ответ…")} required /><button disabled={busy || !message.trim()}><Send size={18} /></button></form>}</Sheet>;
}

function Sheet({ children, close, className = "" }: { children: ReactNode; close: () => void; className?: string }) { return <div className="sheet-layer"><button className="sheet-scrim" onClick={close} aria-label="Закрыть / Close" /><section className={`sheet ${className}`}><i className="sheet-handle" /><button className="sheet-close" onClick={close} aria-label="Закрыть / Close"><X size={17} /></button>{children}</section></div>; }
function ScreenTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: ReactNode }) { return <section className="screen-title"><div><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></div>{action}</section>; }
function State({ loading, error, tr }: { loading: boolean; error: string | null; tr: Tr }) { return <div className="load-state">{loading ? <LoaderCircle className="spin" /> : <CircleHelp />}<span>{loading ? tr("Loading…", "Загрузка…") : error}</span></div>; }
const copySetup = async (notify: Notify, tr: Tr) => { const config = await api<{ subscription_url: string }>("/vpn/config"); await navigator.clipboard.writeText(config.subscription_url); notify(tr("Private link copied", "Приватная ссылка скопирована")); };
const routeFromStart = (value: string | null): Tab => value?.startsWith("plan_") || value?.startsWith("promo_") ? "plans" : value?.startsWith("invite_") ? "family" : value?.startsWith("ticket_") ? "more" : "home";
const initials = (value: string) => value.split(/[\s@._-]+/).filter(Boolean).slice(0, 2).map((part) => part[0].toUpperCase()).join("") || "HZ";
const money = (minor: number, currency: string) => new Intl.NumberFormat("ru-RU", { style: "currency", currency, maximumFractionDigits: 0 }).format(minor / 100);
const status = (value: string, tr: Tr) => ({ waiting_user: tr("Reply waiting", "Ждёт вас"), open: tr("Open", "Открыт"), in_progress: tr("In progress", "В работе"), closed: tr("Closed", "Закрыт") }[value] ?? value);
type Tr = (en: string, ru: string) => string; type Notify = (message: string) => void; type Open = (node: ReactNode | null) => void;
