import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import {
  ArrowLeft, ArrowRight, BadgeCheck, Bell, Check, ChevronRight, CircleHelp, Copy, Crown,
  Gift, Globe2, Headphones, Home, Languages, Link2, LoaderCircle, LockKeyhole, MessageCircle,
  MonitorSmartphone, Moon, MoreHorizontal, Plus, QrCode, Send, ShieldCheck, Smartphone, Sparkles, Sun,
  TicketCheck, Trash2, Upload, UserPlus, UsersRound, Wifi, X, Zap, type LucideIcon,
} from "lucide-react";
import { api, authenticateTelegram, demoMode, hasSession, key, type Device, type FamilyGroup, type Overview, type Payment, type Plan, type PromoPreview, type ReferralStatistics, type Ticket, type TicketDetail } from "./api";
import { tg } from "./telegram";

type Locale = "ru" | "en";
type Theme = "dark" | "light";
type Tab = "home" | "plans" | "devices" | "family" | "more";
interface Load<T> { data: T | null; loading: boolean; error: string | null; reload: () => void; setData: (value: T) => void }

const nav: Array<{ id: Tab; icon: LucideIcon; en: string; ru: string }> = [
  { id: "home", icon: Home, en: "Home", ru: "Главная" },
  { id: "plans", icon: Crown, en: "Plans", ru: "Тарифы" },
  { id: "devices", icon: MonitorSmartphone, en: "Devices", ru: "Устройства" },
  { id: "family", icon: UsersRound, en: "Family", ru: "Семья" },
  { id: "more", icon: MoreHorizontal, en: "More", ru: "Ещё" },
];

function useResource<T>(path: string, enabled = true): Load<T> {
  const [revision, setRevision] = useState(0); const [state, setState] = useState<Omit<Load<T>, "reload" | "setData">>({ data: null, loading: enabled, error: null });
  useEffect(() => { if (!enabled) return; let active = true; setState((value) => ({ ...value, loading: true, error: null })); api<T>(path).then((data) => active && setState({ data, loading: false, error: null })).catch((error: unknown) => active && setState({ data: null, loading: false, error: error instanceof Error ? error.message : "Request failed" })); return () => { active = false; }; }, [path, revision, enabled]);
  return { ...state, reload: () => setRevision((value) => value + 1), setData: (data) => setState({ data, loading: false, error: null }) };
}

export default function App() {
  const [ready, setReady] = useState(hasSession()); const [error, setError] = useState<string | null>(null);
  const [locale, setLocale] = useState<Locale>(() => {
    const stored = localStorage.getItem("hazbit-tma-locale");
    if (stored === "ru" || stored === "en") return stored;
    return tg.user?.language_code?.startsWith("en") ? "en" : "ru";
  });
  const [theme, setTheme] = useState<Theme>(() => localStorage.getItem("hazbit-tma-theme") === "light" ? "light" : "dark");
  const [tab, setTab] = useState<Tab>(() => routeFromStart(tg.startParam)); const [overlay, setOverlay] = useState<ReactNode | null>(null); const [toast, setToast] = useState<string | null>(null);
  const tr = useCallback((en: string, ru: string) => locale === "ru" ? ru : en, [locale]);
  const overview = useResource<Overview>("/portal/overview", ready);

  useEffect(() => tg.boot(), []);
  useEffect(() => { localStorage.setItem("hazbit-tma-locale", locale); document.documentElement.lang = locale; }, [locale]);
  useEffect(() => { localStorage.setItem("hazbit-tma-theme", theme); document.documentElement.dataset.theme = theme; tg.appearance(theme); }, [theme]);
  useEffect(() => { if (ready) return; authenticateTelegram().then(async () => { setReady(true); const start = tg.startParam; if (start?.startsWith("invite_")) { await api("/family/invitations/accept", { method: "POST", body: JSON.stringify({ token: start.slice(7) }) }); setTab("family"); setToast(tr("Family invitation accepted", "Приглашение в семью принято")); } }).catch((value: unknown) => setError(value instanceof Error ? value.message : tr("Telegram authentication failed", "Не удалось войти через Telegram"))); }, [ready, tr]);
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(null), 2400); return () => window.clearTimeout(id); }, [toast]);
  useEffect(() => tg.back(overlay ? () => setOverlay(null) : null), [overlay]);

  const go = (next: Tab) => { tg.haptic("selection"); setTab(next); setOverlay(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  if (!ready) return <LaunchScreen error={error} retry={() => { setError(null); void authenticateTelegram().then(() => setReady(true)).catch((value: unknown) => setError(value instanceof Error ? value.message : tr("Authentication failed", "Не удалось выполнить вход"))); }} tr={tr} />;
  if (!overview.data) return <LaunchScreen error={overview.error} tr={tr} />;
  const data = overview.data;
  const notify = (message: string) => { tg.haptic("success"); setToast(message); };
  const screen = tab === "home" ? <HomeScreen overview={data} tr={tr} go={go} notify={notify} />
    : tab === "plans" ? <PlansScreen current={data.subscription?.plan_slug ?? null} tr={tr} notify={notify} open={setOverlay} />
    : tab === "devices" ? <DevicesScreen overview={data} tr={tr} notify={notify} open={setOverlay} />
    : tab === "family" ? <FamilyScreen identity={data.user.id} tr={tr} notify={notify} open={setOverlay} />
    : <MoreScreen overview={data} locale={locale} setLocale={setLocale} theme={theme} setTheme={setTheme} tr={tr} notify={notify} open={setOverlay} />;

  return <div className="tma-frame"><header className="tma-header"><Brand /><div className="header-actions">{demoMode && <span className="demo"><Sparkles size={11} /> DEMO</span>}<button aria-label={theme === "dark" ? tr("Switch to light theme", "Включить светлую тему") : tr("Switch to dark theme", "Включить тёмную тему")} onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>{theme === "dark" ? <Sun size={18} /> : <Moon size={18} />}</button><button className="notification-control" aria-label={tr("Notifications", "Уведомления")} onClick={() => setToast(tr("No new notifications", "Новых уведомлений нет"))}><Bell size={18} /><i /></button><span className="avatar">{initials(data.user.public_name ?? tg.user?.first_name ?? "H")}</span></div></header><main className="tma-content">{screen}</main><nav className="tma-dock" aria-label={tr("Mini App navigation", "Навигация Mini App")}>{nav.map(({ id, icon: Icon, en, ru }) => <button key={id} className={tab === id ? "active" : ""} onClick={() => go(id)}><Icon size={20} /><span>{tr(en, ru)}</span>{id === "more" && data.open_ticket_count > 0 && <i />}</button>)}</nav>{overlay}{toast && <div className="tma-toast"><Check size={15} />{toast}</div>}</div>;
}

function LaunchScreen({ error, retry, tr }: { error: string | null; retry?: () => void; tr: (en: string, ru: string) => string }) {
  return <main className="launch"><div className="launch-radar"><i /><i /><i /><span><ShieldCheck size={38} /></span></div><Brand /><h1>{error ? tr("Unable to open Hazbit", "Не удалось открыть Hazbit") : tr("Opening your private space", "Открываем приватное пространство")}</h1><p>{error ?? tr("Verifying Telegram session and synchronizing your protection.", "Проверяем Telegram-сессию и синхронизируем защиту.")}</p>{error ? <button onClick={retry}><ArrowRight size={16} /> {tr("Try again", "Попробовать снова")}</button> : <LoaderCircle className="spin" size={20} />}</main>;
}

function HomeScreen({ overview, tr, go, notify }: { overview: Overview; tr: Tr; go: (tab: Tab) => void; notify: Notify }) {
  const end = overview.subscription?.current_period_ends_at; const days = end ? Math.max(0, Math.ceil((new Date(end).getTime() - Date.now()) / 86_400_000)) : 0; const connected = overview.vpn?.observed_status === "active";
  return <div className="screen-stack"><section className="welcome"><p>{tr("Good to see you", "Рады вас видеть")},</p><h1>{overview.user.public_name ?? tg.user?.first_name ?? "Hazbit"}</h1></section><section className={`tunnel-card ${connected ? "connected" : ""}`}><div className="mini-radar"><i /><i /><i /><span><ShieldCheck size={30} /></span></div><span className="signal-label"><b /> {connected ? tr("Protected now", "Сейчас под защитой") : tr("Ready to connect", "Готово к подключению")}</span><h2>{connected ? tr("Your private route is stable", "Приватный маршрут стабилен") : tr("Connection is paused", "Подключение приостановлено")}</h2><p>{tr("VLESS · Automatic routing", "VLESS · Автоматический маршрут")}</p><button onClick={() => go("devices")}><Zap size={16} /> {tr("Connect a device", "Подключить устройство")}</button></section><section className="pulse-grid"><button onClick={() => go("plans")}><span className="pulse-icon mint"><Crown size={19} /></span><small>{tr("Subscription", "Подписка")}</small><b>{overview.subscription?.plan_name ?? "—"}</b><em>{days} {tr("days", "дней")}</em></button><button onClick={() => go("devices")}><span className="pulse-icon blue"><MonitorSmartphone size={19} /></span><small>{tr("Devices", "Устройства")}</small><b>{overview.active_device_count}<em> / {overview.subscription?.device_limit ?? 0}</em></b><span>{tr("Active slots", "Активные слоты")}</span></button></section><section className="family-signal" onClick={() => go("family")} role="button" tabIndex={0}><div className="people-stack"><span>A</span><span>T</span><span>S</span></div><div><small>{tr("Shared protection", "Общая защита")}</small><b>{overview.family_group_name ?? tr("Create a family", "Создать семью")}</b></div><ChevronRight size={18} /></section><section className="action-strip"><button onClick={() => copySetup(notify, tr)}><QrCode size={19} /><span><b>{tr("Quick setup", "Быстрая настройка")}</b><small>{tr("Copy private link", "Скопировать приватную ссылку")}</small></span></button><button onClick={() => go("more")}><Headphones size={19} /><span><b>{tr("Support", "Поддержка")}</b><small>{overview.open_ticket_count ? tr("Reply waiting", "Есть новый ответ") : tr("Online", "Онлайн")}</small></span></button></section></div>;
}

function PlansScreen({ current, tr, notify, open }: { current: string | null; tr: Tr; notify: Notify; open: Open }) {
  const plans = useResource<Plan[]>("/portal/plans"); const deepLink = tg.startParam; const requestedPlan = deepLink?.startsWith("plan_") ? deepLink.slice(5) : null; const [promo, setPromo] = useState(deepLink?.startsWith("promo_") ? deepLink.slice(6).toUpperCase() : ""); const [preview, setPreview] = useState<PromoPreview | null>(null); const [checking, setChecking] = useState(false);
  const orderedPlans = useMemo(() => plans.data ? [...plans.data].sort((left, right) => Number(right.slug === requestedPlan) - Number(left.slug === requestedPlan)) : null, [plans.data, requestedPlan]);
  const checkPromo = async (event: FormEvent) => { event.preventDefault(); setChecking(true); try { const value = await api<PromoPreview>("/promo-codes/preview", { method: "POST", body: JSON.stringify({ code: promo }) }); setPreview(value); notify(tr("Promo code applied", "Промокод применён")); } finally { setChecking(false); } };
  return <div className="screen-stack"><ScreenTitle eyebrow={tr("Choose access", "Выберите доступ")} title={tr("Protection that fits", "Защита под ваши задачи")} text={tr("Change the plan without losing devices or remaining days.", "Меняйте тариф без потери устройств и оставшихся дней.")} />{!orderedPlans ? <State loading={plans.loading} error={plans.error} tr={tr} /> : <section className="tma-plans">{orderedPlans.map((plan) => { const price = plan.prices[0]; const active = plan.slug === current; return <article key={plan.id} className={`${plan.slug} ${active ? "active" : ""}`}><header><span>{plan.slug === "family" ? <UsersRound /> : plan.slug === "premium" ? <Crown /> : <ShieldCheck />}</span>{active && <em><BadgeCheck size={12} /> {tr("Current", "Текущий")}</em>}</header><h3>{plan.name}</h3><p>{plan.slug === "family" ? tr("For the people closest to you.", "Для самых близких людей.") : plan.slug === "premium" ? tr("More devices and priority routes.", "Больше устройств и приоритетные маршруты.") : tr("Simple private access.", "Простой приватный доступ.")}</p><div className="tma-price"><b>{money(price.amount_minor, price.currency)}</b><small>/ {tr("month", "месяц")}</small></div><ul><li><Check />{plan.device_limit} {tr("devices", "устройств")}</li><li><Check />{plan.family_member_limit || 1} {tr("people", "участников")}</li></ul><button disabled={active} onClick={() => open(<PurchaseSheet plan={plan} promo={preview?.code ?? null} tr={tr} notify={notify} close={() => open(null)} />)}>{active ? tr("Active", "Активен") : tr("Choose", "Выбрать")}<ArrowRight size={15} /></button></article>; })}</section>}<form className="promo-bar" onSubmit={checkPromo}><span><Gift size={18} /><input value={promo} onChange={(event) => setPromo(event.target.value.toUpperCase())} placeholder={tr("Promo code", "Промокод")} required /></span><button disabled={checking}>{checking ? <LoaderCircle className="spin" size={15} /> : tr("Apply", "Применить")}</button></form>{preview && <div className="promo-result"><Sparkles size={16} /><b>{preview.code}</b><span>−{preview.value}%</span></div>}</div>;
}

function PurchaseSheet({ plan, promo, tr, notify, close }: { plan: Plan; promo: string | null; tr: Tr; notify: Notify; close: () => void }) {
  const price = plan.prices[0]; const [busy, setBusy] = useState(false); const buy = useCallback(async () => { setBusy(true); try { const payment = await api<Payment & { telegram_invoice_url?: string }>("/payments/intents", { method: "POST", headers: { "Idempotency-Key": key("tma-payment") }, body: JSON.stringify({ plan_price_id: price.id, promo_code: promo }) }); if (payment.telegram_invoice_url && tg.available) tg.openInvoice(payment.telegram_invoice_url, (status) => { if (status === "paid") notify(tr("Payment completed", "Платёж завершён")); else notify(tr("Invoice opened", "Счёт открыт")); close(); }); else { notify(tr("Payment intent created", "Платёж создан — загрузите чек на сайте")); close(); } } catch { tg.haptic("error"); } finally { setBusy(false); } }, [close, notify, plan, price.id, promo, tr]);
  useEffect(() => tg.main(tr(`Pay ${money(price.amount_minor, price.currency)}`, `Оплатить ${money(price.amount_minor, price.currency)}`), buy, busy), [buy, busy, price.amount_minor, price.currency, tr]);
  return <Sheet close={close}><div className="sheet-symbol"><Crown size={23} /></div><p className="eyebrow">{tr("TELEGRAM INVOICE", "СЧЁТ TELEGRAM")}</p><h2>{plan.name}</h2><p>{tr("Telegram will show the final payment confirmation in its native invoice window.", "Telegram покажет финальное подтверждение в нативном окне счёта.")}</p><div className="invoice-summary"><span>{tr("Plan", "Тариф")}<b>{plan.name}</b></span><span>{tr("Devices", "Устройства")}<b>{plan.device_limit}</b></span>{promo && <span>{tr("Promo", "Промокод")}<b>{promo}</b></span>}<strong>{tr("Total", "Итого")}<b>{money(price.amount_minor, price.currency)}</b></strong></div><button className="sheet-primary" disabled={busy} onClick={buy}>{busy ? <LoaderCircle className="spin" size={17} /> : <ArrowRight size={17} />} {tr("Continue to payment", "Перейти к оплате")}</button></Sheet>;
}

function DevicesScreen({ overview, tr, notify, open }: { overview: Overview; tr: Tr; notify: Notify; open: Open }) {
  const devices = useResource<Device[]>("/devices"); const remove = async (device: Device) => { await api(`/devices/${device.id}`, { method: "DELETE" }); devices.reload(); notify(tr("Device removed", "Устройство удалено")); };
  return <div className="screen-stack"><ScreenTitle eyebrow={tr("Private perimeter", "Приватный периметр")} title={tr("Your devices", "Ваши устройства")} text={`${devices.data?.length ?? 0} / ${overview.subscription?.device_limit ?? 0} ${tr("slots in use", "слотов занято")}`} action={<button className="round-add" onClick={() => open(<AddDeviceSheet tr={tr} close={() => open(null)} done={() => { open(null); devices.reload(); notify(tr("Device reserved", "Устройство добавлено")); }} />)}><Plus size={19} /></button>} /><div className="slot-meter">{Array.from({ length: overview.subscription?.device_limit ?? 0 }, (_, index) => <i className={index < (devices.data?.length ?? 0) ? "used" : ""} key={index} />)}</div>{!devices.data ? <State loading={devices.loading} error={devices.error} tr={tr} /> : <section className="device-list">{devices.data.map((device) => <article key={device.id}><span className="device-glyph">{device.platform?.includes("mac") ? <MonitorSmartphone /> : <Smartphone />}</span><div><b>{device.label}</b><small>{device.platform} · {device.status === "active" ? tr("Connected", "Подключено") : tr("Provisioning", "Подключается")}</small></div><button aria-label={tr(`Remove ${device.label}`, `Удалить ${device.label}`)} onClick={() => remove(device)}><Trash2 size={15} /></button></article>)}</section>}<button className="setup-card" onClick={() => copySetup(notify, tr)}><span><QrCode size={23} /></span><div><b>{tr("Private setup link", "Приватная ссылка настройки")}</b><small>{tr("Copy once, then open in your VPN app", "Скопируйте и откройте в VPN-приложении")}</small></div><Copy size={17} /></button></div>;
}

function AddDeviceSheet({ tr, close, done }: { tr: Tr; close: () => void; done: () => void }) {
  const [label, setLabel] = useState(""); const [platform, setPlatform] = useState("iOS"); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api("/devices", { method: "POST", headers: { "Idempotency-Key": key("tma-device") }, body: JSON.stringify({ label, platform, hwid: crypto.randomUUID().replaceAll("-", "").slice(0, 24), os_version: "unknown", device_model: label }) }); done(); } finally { setBusy(false); } };
  return <Sheet close={close}><form onSubmit={submit}><div className="sheet-symbol"><Smartphone size={22} /></div><p className="eyebrow">{tr("NEW SECURE SLOT", "НОВОЕ ЗАЩИЩЁННОЕ УСТРОЙСТВО")}</p><h2>{tr("Add a device", "Добавить устройство")}</h2><label>{tr("Device name", "Название устройства")}<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder={tr("My iPhone", "Мой iPhone")} required /></label><label>{tr("Platform", "Платформа")}<select value={platform} onChange={(event) => setPlatform(event.target.value)}><option>iOS</option><option>Android</option><option>macOS</option><option>Windows</option><option>Linux</option></select></label><button className="sheet-primary" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <Plus size={17} />} {tr("Reserve slot", "Зарезервировать слот")}</button></form></Sheet>;
}

function FamilyScreen({ identity, tr, notify, open }: { identity: string; tr: Tr; notify: Notify; open: Open }) {
  const family = useResource<FamilyGroup>("/family/group"); const group = family.data; if (!group) return <State loading={family.loading} error={family.error} tr={tr} />; const owner = group.owner_user_id === identity;
  return <div className="screen-stack"><section className="family-card"><div className="family-cloud"><span>A</span><i>T</i><i>S</i><b><ShieldCheck size={23} /></b></div><p className="eyebrow">{tr("FAMILY SHIELD", "СЕМЕЙНАЯ ЗАЩИТА")}</p><h1>{group.name}</h1><p>{tr("Separate accounts. One private perimeter.", "Отдельные аккаунты. Один приватный периметр.")}</p></section><section className="family-capacity"><div><small>{tr("People", "Участники")}</small><b>{group.active_member_count} / {group.member_limit}</b></div><span /><div><small>{tr("Devices", "Устройства")}</small><b>{group.active_device_count} / {group.device_limit}</b></div></section><section className="member-list"><header><h3>{tr("Protected people", "Защищённые участники")}</h3>{owner && <button onClick={() => open(<InviteSheet group={group} tr={tr} close={() => open(null)} done={() => { open(null); family.reload(); notify(tr("Invitation sent", "Приглашение создано")); }} />)}><UserPlus size={16} />{tr("Invite", "Пригласить")}</button>}</header>{group.members.map((member) => <article key={member.id}><span>{initials(member.email ?? "H")}</span><div><b>{member.email}</b><small>{member.role === "owner" ? tr("Owner", "Владелец") : tr("Member", "Участник")}</small></div>{member.role === "owner" && <Crown size={15} />}</article>)}</section>{group.invitations.filter((item) => item.status === "pending").length > 0 && <section className="pending-card"><small>{tr("Waiting for acceptance", "Ожидают принятия")}</small>{group.invitations.filter((item) => item.status === "pending").map((item) => <div key={item.id}><MessageCircle size={15} /><b>{item.invited_email}</b><span>{tr("Sent", "Отправлено")}</span></div>)}</section>}</div>;
}

function InviteSheet({ group, tr, close, done }: { group: FamilyGroup; tr: Tr; close: () => void; done: () => void }) {
  const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api(`/family/groups/${group.id}/invitations`, { method: "POST", body: JSON.stringify({ invited_email: email }) }); done(); } finally { setBusy(false); } };
  return <Sheet close={close}><form onSubmit={submit}><div className="sheet-symbol"><UserPlus size={22} /></div><p className="eyebrow">{tr("FAMILY INVITE", "СЕМЕЙНОЕ ПРИГЛАШЕНИЕ")}</p><h2>{tr("Share protection", "Поделиться защитой")}</h2><p>{tr("The person will receive a private link and keep a separate Hazbit account.", "Человек получит приватную ссылку и сохранит отдельный аккаунт Hazbit.")}</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="person@example.com" required /></label><button className="sheet-primary" disabled={busy}><Send size={17} /> {tr("Create invitation", "Создать приглашение")}</button></form></Sheet>;
}

function MoreScreen({ overview, locale, setLocale, theme, setTheme, tr, notify, open }: { overview: Overview; locale: Locale; setLocale: (locale: Locale) => void; theme: Theme; setTheme: (theme: Theme) => void; tr: Tr; notify: Notify; open: Open }) {
  const rewards = useResource<ReferralStatistics>("/referrals/statistics"); const tickets = useResource<Ticket[]>("/tickets"); const share = () => { const url = rewards.data?.code?.share_url; if (url) tg.openTelegram(`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(tr("Join my private Hazbit network", "Присоединяйся к моей приватной сети Hazbit"))}`); };
  useEffect(() => { const start = tg.startParam; if (!start?.startsWith("ticket_") || !tickets.data) return; const target = start.slice(7); const ticket = tickets.data.find((item) => item.id === target || String(item.public_number) === target); if (ticket) open(<TicketSheet ticket={ticket} tr={tr} close={() => open(null)} />); }, [tickets.data]);
  return <div className="screen-stack"><ScreenTitle eyebrow={tr("Your Hazbit", "Ваш Hazbit")} title={tr("More control", "Больше возможностей")} text={tr("Rewards, support and Mini App preferences.", "Бонусы, поддержка и настройки Mini App.")} /><section className="reward-card"><span><Gift size={24} /></span><div><small>{tr("Bonus days", "Бонусные дни")}</small><h3>+{rewards.data?.granted_referrer_days ?? 0}</h3><p>{rewards.data?.code?.code ?? "—"}</p></div><button onClick={share}><Send size={16} />{tr("Share", "Поделиться")}</button></section><section className="more-section"><header><h3>{tr("Support", "Поддержка")}</h3><span>{overview.open_ticket_count}</span></header>{tickets.data?.map((ticket) => <button className="ticket-row" key={ticket.id} onClick={() => open(<TicketSheet ticket={ticket} tr={tr} close={() => open(null)} />)}><span><MessageCircle size={17} /></span><div><b>{ticket.subject}</b><small>#{ticket.public_number} · {status(ticket.status, tr)}</small></div><ChevronRight size={16} /></button>)}</section><section className="more-section settings"><header><h3>{tr("Mini App settings", "Настройки Mini App")}</h3></header><div className="setting"><span>{theme === "dark" ? <Moon size={18} /> : <Sun size={18} />}<div><b>{tr("Appearance", "Оформление")}</b><small>{theme === "dark" ? tr("Dark theme", "Тёмная тема") : tr("Light theme", "Светлая тема")}</small></div></span><div className="lang-choice theme-choice"><button className={theme === "dark" ? "active" : ""} onClick={() => setTheme("dark")}>{tr("Dark", "Тёмная")}</button><button className={theme === "light" ? "active" : ""} onClick={() => setTheme("light")}>{tr("Light", "Светлая")}</button></div></div><div className="setting"><span><Languages size={18} /><div><b>{tr("Language", "Язык")}</b><small>{tr("Interface language", "Язык интерфейса")}</small></div></span><div className="lang-choice"><button className={locale === "ru" ? "active" : ""} onClick={() => setLocale("ru")}>RU</button><button className={locale === "en" ? "active" : ""} onClick={() => setLocale("en")}>EN</button></div></div><div className="setting"><span><LockKeyhole size={18} /><div><b>{tr("Telegram session", "Telegram-сессия")}</b><small>{tr("Signed initData and rotating JWT", "Подписанный initData и ротация JWT")}</small></div></span><BadgeCheck className="verified" size={18} /></div></section><section className="telegram-profile"><span className="large-avatar">{initials(overview.user.public_name ?? tg.user?.first_name ?? "H")}</span><div><b>{overview.user.public_name ?? tg.user?.first_name}</b><small>{overview.user.telegram_username ? `@${overview.user.telegram_username}` : `Telegram ID ${overview.user.telegram_user_id ?? "—"}`}</small></div><ShieldCheck size={19} /></section></div>;
}

function TicketSheet({ ticket, tr, close }: { ticket: Ticket; tr: Tr; close: () => void }) {
  const detail = useResource<TicketDetail>(`/tickets/${ticket.id}`); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const send = async (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; setBusy(true); try { await api(`/tickets/${ticket.id}/messages`, { method: "POST", headers: { "Idempotency-Key": key("tma-ticket") }, body: JSON.stringify({ body: message }) }); setMessage(""); detail.reload(); tg.haptic("success"); } finally { setBusy(false); } };
  return <Sheet close={close} className="chat-sheet"><header className="chat-head"><button onClick={close}><ArrowLeft size={18} /></button><div><small>{tr("Ticket", "Тикет")} #{ticket.public_number}</small><b>{ticket.subject}</b></div><span className="online" /></header><div className="chat-messages">{detail.loading ? <LoaderCircle className="spin" /> : detail.data?.messages.map((item) => <article className={item.sender_user_id ? "mine" : "support"} key={item.id}><small>{item.sender_user_id ? tr("You", "Вы") : "Hazbit Support"}</small><p>{item.body}</p></article>)}</div>{ticket.status !== "closed" && <form className="chat-composer" onSubmit={send}><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder={tr("Write a reply…", "Напишите ответ…")} required /><button disabled={busy || !message.trim()}><Send size={18} /></button></form>}</Sheet>;
}

function Sheet({ children, close, className = "" }: { children: ReactNode; close: () => void; className?: string }) { return <div className="sheet-layer"><button className="sheet-scrim" onClick={close} aria-label="Закрыть / Close" /><section className={`sheet ${className}`}><i className="sheet-handle" /><button className="sheet-close" onClick={close} aria-label="Закрыть / Close"><X size={17} /></button>{children}</section></div>; }
function ScreenTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: ReactNode }) { return <section className="screen-title"><div><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></div>{action}</section>; }
function State({ loading, error, tr }: { loading: boolean; error: string | null; tr: Tr }) { return <div className="load-state">{loading ? <LoaderCircle className="spin" /> : <CircleHelp />}<span>{loading ? tr("Loading…", "Загрузка…") : error}</span></div>; }
function Brand() { return <div className="tma-brand"><span><i /><i /><i /></span><b>HAZBIT<small>TELEGRAM</small></b></div>; }
const copySetup = async (notify: Notify, tr: Tr) => { const config = await api<{ subscription_url: string }>("/vpn/config"); await navigator.clipboard.writeText(config.subscription_url); notify(tr("Private link copied", "Приватная ссылка скопирована")); };
const routeFromStart = (value: string | null): Tab => value?.startsWith("plan_") || value?.startsWith("promo_") ? "plans" : value?.startsWith("invite_") ? "family" : value?.startsWith("ticket_") ? "more" : "home";
const initials = (value: string) => value.split(/[\s@._-]+/).filter(Boolean).slice(0, 2).map((part) => part[0].toUpperCase()).join("") || "HZ";
const money = (minor: number, currency: string) => new Intl.NumberFormat("ru-RU", { style: "currency", currency, maximumFractionDigits: 0 }).format(minor / 100);
const status = (value: string, tr: Tr) => ({ waiting_user: tr("Reply waiting", "Ждёт вас"), open: tr("Open", "Открыт"), in_progress: tr("In progress", "В работе"), closed: tr("Closed", "Закрыт") }[value] ?? value);
type Tr = (en: string, ru: string) => string; type Notify = (message: string) => void; type Open = (node: ReactNode | null) => void;
