import { ArrowLeft, FileCheck2, Headphones, Mail, MessageCircle, ShieldCheck } from "lucide-react";
import { PublicHeader } from "../../components/layout/PublicHeader";
import { legalConfig } from "../../config/legal";
import { useI18n } from "../../i18n";
import type { Theme } from "../../types";
import "./legal.css";

export type LegalRoute = "privacy" | "terms" | "contacts";

interface Props { route: LegalRoute; theme: Theme; onThemeChange: (theme: Theme) => void; authenticated: boolean; onAccountAction: () => void }

export function PublicLegalPage({ route, theme, onThemeChange, authenticated, onAccountAction }: Props) {
  const { t } = useI18n();
  const content = route === "privacy" ? <Privacy /> : route === "terms" ? <Terms /> : <Contacts />;
  return <main className="legal-page"><div className="public-page__mesh" /><PublicHeader theme={theme} onThemeChange={onThemeChange} authenticated={authenticated} onAccountAction={onAccountAction} /><div className="legal-wrap"><a className="legal-back" href="#top"><ArrowLeft />{t("Back to website", "Вернуться на сайт")}</a>{content}</div><LegalFooter /></main>;
}

function Privacy() {
  const { t } = useI18n();
  return <article className="legal-document"><LegalHead icon={ShieldCheck} eyebrow={t("LEGAL · PRIVACY", "ДОКУМЕНТЫ · КОНФИДЕНЦИАЛЬНОСТЬ")} title={t("Privacy Policy", "Политика конфиденциальности")} /><p>{t(`Effective date: ${legalConfig.effectiveDate}. This policy explains how ${legalConfig.operatorName} processes data while operating ${legalConfig.projectName}.`, `Дата вступления в силу: ${legalConfig.effectiveDate}. Политика описывает, как ${legalConfig.operatorName} обрабатывает данные при работе сервиса ${legalConfig.projectName}.`)}</p><LegalSections items={[
    [t("1. What we collect", "1. Какие данные мы обрабатываем"), t("Account identifiers (email and Telegram ID), authentication and security events, IP address, device fingerprint, device labels, subscription and wallet operations, support messages and technical diagnostics. Payment card or bank account details are entered on the Platega side and are not stored by Hazbit.", "Идентификаторы аккаунта (email и Telegram ID), события входа и безопасности, IP-адрес, отпечаток и названия устройств, данные подписки и операций кошелька, обращения в поддержку и техническую диагностику. Данные банковской карты или счёта вводятся на стороне Platega и не хранятся в Hazbit.")],
    [t("2. Why we process data", "2. Для чего нужны данные"), t("To create and protect an account, provide VLESS access, manage devices and family groups, process wallet top-ups and subscription debits, prevent abuse, provide support and comply with legal obligations.", "Чтобы создать и защитить аккаунт, предоставить VLESS-доступ, управлять устройствами и семейными группами, обрабатывать пополнения и списания за подписку, предотвращать злоупотребления, оказывать поддержку и исполнять требования закона.")],
    [t("3. Legal grounds", "3. Основания обработки"), t("Performance of the user agreement, user consent where required, legitimate security interests and obligations imposed by applicable law.", "Исполнение пользовательского соглашения, согласие пользователя в предусмотренных случаях, законный интерес в обеспечении безопасности и обязанности по применимому законодательству.")],
    [t("4. Recipients and processors", "4. Получатели и обработчики"), t("Necessary data may be shared with hosting, email, Telegram, Remnawave infrastructure and Platega payment services solely to deliver the service. We do not sell personal data.", "Необходимые данные могут передаваться поставщикам хостинга и email, Telegram, инфраструктуре Remnawave и платёжному сервису Platega исключительно для работы сервиса. Мы не продаём персональные данные.")],
    [t("5. Storage and protection", "5. Хранение и защита"), t("We apply access controls, role separation, encrypted transport, audit logs and limited retention. Data is retained for as long as the account or legal obligations require, then deleted or anonymized.", "Мы применяем контроль доступа, разделение ролей, шифрование транспорта, аудит действий и ограниченные сроки хранения. Данные хранятся пока действует аккаунт или этого требует закон, затем удаляются или обезличиваются.")],
    [t("6. Your rights", "6. Ваши права"), t(`You may request access, correction, restriction or deletion by contacting ${legalConfig.supportEmail}. Some accounting and security records may be retained where required by law.`, `Вы можете запросить доступ, исправление, ограничение обработки или удаление через ${legalConfig.supportEmail}. Отдельные расчётные и защитные записи могут храниться в установленных законом случаях.`)],
    [t("7. Updates", "7. Изменения политики"), t("The current version and effective date are always published on this page. Material changes may additionally be announced in the account or Mini App.", "Актуальная редакция и дата всегда опубликованы на этой странице. О существенных изменениях мы можем дополнительно сообщить в кабинете или Mini App.")],
  ]} /></article>;
}

function Terms() {
  const { t } = useI18n();
  return <article className="legal-document"><LegalHead icon={FileCheck2} eyebrow={t("LEGAL · SERVICE", "ДОКУМЕНТЫ · СЕРВИС")} title={t("User Agreement", "Пользовательское соглашение")} /><p>{t(`Effective date: ${legalConfig.effectiveDate}. By creating an account or paying for a tariff, the user accepts this agreement with ${legalConfig.operatorName}, operator of ${legalConfig.projectName}.`, `Дата вступления в силу: ${legalConfig.effectiveDate}. Создавая аккаунт или оплачивая тариф, пользователь принимает настоящее соглашение с ${legalConfig.operatorName}, оператором ${legalConfig.projectName}.`)}</p><LegalSections items={[
    [t("1. Service", "1. Предмет соглашения"), t("Hazbit provides time-limited access to private VLESS network routes, a client account, device and family management, wallet functions and support according to the selected tariff.", "Hazbit предоставляет срочный доступ к приватным VLESS-маршрутам, личный кабинет, управление устройствами и семьёй, кошелёк и поддержку в соответствии с выбранным тарифом.")],
    [t("2. Account", "2. Аккаунт"), t("The user must provide current information, protect access to email and Telegram, and immediately report unauthorized access. One person may not abuse trials, referrals, promos or payment mechanisms.", "Пользователь обязан указывать актуальные данные, защищать доступ к почте и Telegram и сообщать о несанкционированном доступе. Запрещено злоупотреблять пробными периодами, рефералами, промокодами и платежами.")],
    [t("3. Tariffs and payment", "3. Тарифы и оплата"), t("Current prices, periods and limits are displayed before purchase. The user first tops up the Hazbit balance through Platega and then confirms a tariff debit. Access begins or extends after a successful wallet debit.", "Актуальные цены, сроки и лимиты показаны до покупки. Пользователь пополняет баланс Hazbit через Platega, затем подтверждает списание за тариф. Доступ активируется или продлевается после успешного списания.")],
    [t("4. Automatic renewal", "4. Автопродление"), t("If enabled by the user, the tariff price is debited only from the Hazbit balance at the end of the paid period. It can be disabled at any time. If the balance is insufficient, renewal is not performed and access may stop after the paid period.", "Если пользователь включил автопродление, стоимость тарифа списывается только с баланса Hazbit по окончании оплаченного периода. Опцию можно отключить в любое время. При недостаточном балансе продление не выполняется, а доступ может завершиться вместе с оплаченным периодом.")],
    [t("5. Refunds", "5. Возвраты"), t(`Refund requests are reviewed through support at ${legalConfig.supportEmail}. The amount depends on service delivery, payment status and mandatory consumer rules. Chargebacks may result in a corresponding wallet reversal and access suspension.`, `Запросы на возврат рассматриваются через поддержку ${legalConfig.supportEmail}. Сумма зависит от объёма оказанной услуги, статуса платежа и обязательных норм защиты потребителей. Возврат через платёжную систему может привести к обратному списанию с баланса и приостановке доступа.`)],
    [t("6. Acceptable use", "6. Допустимое использование"), t("The service may not be used for unlawful activity, attacks, spam, distribution of malware, infringement of third-party rights or attempts to bypass service limits. Access may be restricted to protect users and infrastructure.", "Запрещено использовать сервис для противоправных действий, атак, спама, распространения вредоносного ПО, нарушения прав третьих лиц и обхода лимитов сервиса. Доступ может быть ограничен для защиты пользователей и инфраструктуры.")],
    [t("7. Availability and liability", "7. Доступность и ответственность"), t("We maintain the service with reasonable care but cannot guarantee uninterrupted operation of external networks, banks, Telegram, providers or user devices. Liability is limited to the extent permitted by applicable law.", "Мы поддерживаем сервис с разумной осмотрительностью, но не гарантируем бесперебойную работу внешних сетей, банков, Telegram, провайдеров и устройств пользователя. Ответственность ограничивается в пределах, допускаемых применимым законом.")],
    [t("8. Support and termination", "8. Поддержка и прекращение"), t(`Questions and claims may be submitted by ticket or email to ${legalConfig.supportEmail}. The user may stop using the service; paid access remains available until the end of its period unless law or a refund decision provides otherwise.`, `Вопросы и претензии можно направить через тикет или на ${legalConfig.supportEmail}. Пользователь вправе прекратить использование; оплаченный доступ действует до конца периода, если закон или решение о возврате не предусматривает иное.`)],
  ]} /></article>;
}

function Contacts() {
  const { t } = useI18n();
  return <article className="legal-document contacts-document"><LegalHead icon={Headphones} eyebrow={t("SUPPORT", "ПОДДЕРЖКА")} title={t("We are here to help", "Мы на связи")} /><p>{t("Use a private support ticket for account, connection, payment and refund questions. You may also contact us directly.", "Создайте приватный тикет по вопросам аккаунта, подключения, оплаты или возврата. Также можно связаться напрямую.")}</p><div className="contact-grid"><a href={`mailto:${legalConfig.supportEmail}`}><Mail /><span><small>Email</small><b>{legalConfig.supportEmail}</b></span></a><a href={`https://t.me/${legalConfig.supportTelegram.replace(/^@/, "")}`} target="_blank" rel="noreferrer"><MessageCircle /><span><small>Telegram</small><b>{legalConfig.supportTelegram}</b></span></a><a href="#support"><Headphones /><span><small>{t("Account", "Личный кабинет")}</small><b>{t("Open a support ticket", "Создать тикет")}</b></span></a></div><section className="operator-card"><small>{t("SERVICE OPERATOR", "ОПЕРАТОР СЕРВИСА")}</small><h2>{legalConfig.operatorName}</h2><p>{legalConfig.projectName} · {t("online customer support", "онлайн-поддержка пользователей")}</p></section></article>;
}

function LegalHead({ icon: Icon, eyebrow, title }: { icon: typeof ShieldCheck; eyebrow: string; title: string }) { return <header className="legal-head"><span><Icon /></span><div><small>{eyebrow}</small><h1>{title}</h1></div></header>; }
function LegalSections({ items }: { items: Array<[string, string]> }) { return <div className="legal-sections">{items.map(([title, copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</div>; }
function LegalFooter() { return <footer className="legal-footer"><span>© 2026 {legalConfig.projectName}</span><nav><a href="#privacy">Конфиденциальность</a><a href="#terms">Соглашение</a><a href="#contacts">Контакты</a></nav></footer>; }
